Shatters buff
PMC-Unga-Marines/Unga-Marines pull request #310
Opened 2024-09-13 07:48 UTC by homexp13

## `Основные изменения`

флечеты и мосинка/свд наносят шатер

SR-127 убрал сандер и добавил эффект замедление

2024-09-13 09:15 UTC, Tatarla commented
Наводку на снайпу давай

2024-09-13 13:12 UTC, Helg2 commented on code/modules/projectiles/guns/rifles.dm
> -	reciever_flags = AMMO_RECIEVER_REQUIRES_UNIQUE_ACTION|AMMO_RECIEVER_MAGAZINES|AMMO_RECIEVER_UNIQUE_ACTION_LOCKS|AMMO_RECIEVER_AUTO_EJECT
?

2024-09-13 13:33 UTC, homexp13 commented on code/modules/projectiles/guns/rifles.dm
> -	reciever_flags = AMMO_RECIEVER_REQUIRES_UNIQUE_ACTION|AMMO_RECIEVER_MAGAZINES|AMMO_RECIEVER_UNIQUE_ACTION_LOCKS|AMMO_RECIEVER_AUTO_EJECT
если это оставить он будет на пробел патроны закидывать пытаться, а не режим стрельбы переключать

2024-09-13 13:38 UTC, Helg2 approved these changes

2024-09-17 07:24 UTC, Helg2 requested changes
Убери определение всех звуков связанных с передергиванием ствола.

2024-09-20 07:36 UTC, Helg2 approved these changes

2024-09-20 07:37 UTC, merged