Доработки равагера
PMC-Unga-Marines/Unga-Marines pull request #322
Opened 2024-09-13 19:53 UTC by Waselon

Примо вампиризм убран. Вместо него теперь будет новая примо способность - бессмертие.

Да, просто бессмертие на 5 секунд. КД 35 секунд.

Связка хила от рейджа и вампиризма была довольно сильной, возможно даже слишком.

Продление эндюра теперь опять зависит от силы рейджа, но имеет минимальное значение в 1 секунду.

Да, я специально избегаю слова "нерф".

2024-09-13 20:17 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
> +	to_chat(owner,span_highdanger("We are now mortal again"))
```suggestion
	to_chat(owner, span_highdanger("We are now mortal again."))
```

2024-09-13 20:17 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
> +	to_chat(owner, span_xenodanger("We feel able to be immortal once again"))
```suggestion
	to_chat(owner, span_xenodanger("We are able to become immortal once again."))
```

2024-09-13 20:18 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
> +	desc = "We are too angry to die"
```suggestion
	desc = "We are too angry to die."
```

2024-09-13 20:18 UTC, Helg2 commented on code/datums/keybinding/xeno.dm
> +	hotkey_keys = list("Q")
Нормальный кейбинд бы...

2024-09-13 20:18 UTC, Helg2 commented on code/datums/keybinding/xeno.dm
> +	description = "For the next few moments we will be immune to damage"
```suggestion
	description = "For the next few moments we will be immune to damage."
```

2024-09-13 20:50 UTC, Helg2 approved these changes
Вроде норм

2024-09-15 10:53 UTC, homexp13 requested changes

2024-09-15 10:53 UTC, homexp13 commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
> +	var/health_recovery = RAVAGER_RAGE_HEALTH_RECOVERY_PER_SLASH + RAVAGER_RAGE_HEALTH_RECOVERY_PER_SLASH * rage_power
насрал

2024-09-15 10:57 UTC, Waselon commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
> +	var/health_recovery = RAVAGER_RAGE_HEALTH_RECOVERY_PER_SLASH + RAVAGER_RAGE_HEALTH_RECOVERY_PER_SLASH * rage_power
Так и надо

2024-09-15 10:58 UTC, homexp13 commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
> +	var/health_recovery = RAVAGER_RAGE_HEALTH_RECOVERY_PER_SLASH + RAVAGER_RAGE_HEALTH_RECOVERY_PER_SLASH * rage_power
насрано как кодом так и балансом

2024-09-15 13:07 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
> +	var/health_recovery = RAVAGER_RAGE_HEALTH_RECOVERY_PER_SLASH + RAVAGER_RAGE_HEALTH_RECOVERY_PER_SLASH * rage_power
Скобки поставь на всякий случай.

2024-09-15 13:16 UTC, homexp13 commented on code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
> +	X.status_flags |= GODMODE
через ENABLE_BITFIELD, DISABLE_BITFIELD лучше сделай

2024-10-13 15:50 UTC, merged