Hunter Redone
PMC-Unga-Marines/Unga-Marines pull request #363
Opened 2024-09-17 04:31 UTC by definitelynotspaghetti

## `Основные изменения`

Изменил некоторые абилки Хантера, добавил немного новых.

Инвиз теперь работает иначе, вместо траты плазмы за каждый тайл, тратится одна большая порция(80), инвиз спадает автоматически спустя некоторое время и имеет увеличенный кд.
Стелс атака больше не наносит урона, но заряжается за секунду.
Паунс больше не станит хантера. После паунса дается короткий бафф к скорости атаки. После активации паунса, примо уходит в кд на три секунды.
Хантер теперь имеет пассивное увеличенное уклонение от прожектайлов.
Новая пассивная абилка, с 20% процентным шансом хантер может нанести крит на 300% урона с руки, сама абилка не может сработать два раза подряд и уходит в кд на три секунды после срабатывания.
Еще одна новая пассивка. С каждым ударом хантер теперь с 70% шансом спавнит одну иллюзию в случайном тайле вокруг цели. Каждая иллюзия живет две секунды.
Новое примо. Хантер может телепортироваться на любой свободный тайл к цели, если цель не дальше 7 тайлов. После телепортации получает короткий бафф к скорости атаки. После активации примо, паунс уходит в кд на три секунды.
Абилка сайленс удалена, как и старое примо и крипплинг страйк.

## `Как это улучшит игру`
Полезные абилки добавлены, бесполезные удалены, возможно хантер стал лучше как каста.

## `Ченджлог`

```
:cl: eto_ne_spaghetti_chestno
add: Добавлена пассивка, увеличивающая уклонение прожектайлам.
add: Добавлена пассивка на критический урон.
add: Добавлена пассивка, спавнящая иллюзии вокруг жертвы.
add: Добавлено новое примо. 
add: Добавлена механика баффа атаки после использования паунса и примо
del: Удалено старое примо.
del: Удален крипплинг страйк.
del: Удален Silence.
code: Абилка стелс теперь имеет длительность, и теперь тратит плазму единовременно, а не за каждый пройденный тайл.
balance: Метка хантера больше не имеет КД.
balance: Инвиз теперь тратит 80 плазмы.
/:cl:
```

2024-09-17 05:35 UTC, homexp13 requested changes

2024-09-17 05:35 UTC, homexp13 commented on code/datums/mutable_appearance.dm
> +//	plane = FLOAT_PLANE // No clue why this is 0 by default yet images are on FLOAT_PLANE
НАСРАНО

2024-09-17 07:20 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +
Какой смысл делать это общим варом для ксеносов, если используется он лишь в 1-ой абилке, и как вара для этой абилки его хватит за глаза?

2024-09-17 10:13 UTC, Helg2 commented on code/datums/status_effects/xeno_buffs.dm
> +		X.xeno_caste.attack_delay = CLICK_CD_MELEE
`initial(X.xeno_caste.attack_delay)` сделай, а то ты Хантеру повысишь время атаки с 0.7 до 0.8

2024-09-17 10:13 UTC, Helg2 commented on code/datums/status_effects/xeno_buffs.dm
> +	X.xeno_caste.attack_delay = 4
```suggestion
	X.xeno_caste.attack_delay -= 3
```
Чтобы этот баф можно было применить ко всем, и не париться с балансировкой.

2024-09-17 11:47 UTC, Helg2 commented on code/modules/projectiles/projectile.dm
> +
70% игнора пуль - кринж

2024-09-17 15:29 UTC, homexp13 commented on code/modules/projectiles/projectile.dm
> +
хоть от стелса бы сделал

2024-09-17 15:56 UTC, ChromosomeKiller commented
https://github.com/user-attachments/assets/b6dc87bd-542e-4c31-80de-5a131ec567a0
ви кан онли телепорт ту ливинг беингс)))))

2024-09-20 14:52 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +		return fail_activate()
Добавь проверку на то жив ли моб, или смени текст баллун алёрта, если в этом и есть задумка.

2024-09-26 08:28 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +#define ILLUSION_LIFETIME 5 SECONDS
`undef` бы в конце файла

2024-09-26 08:28 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +		return FALSE
От этого есть смысл какой-то?

2024-09-26 08:29 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +		X.face_atom(target_turf)
```suggestion
```
Дубликат

2024-09-26 08:31 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +		owner.balloon_alert(owner, "We can only teleport to other beings!")
Я бы если честно удалил баллун алёрт, так как он только больше конфузит

2024-09-26 08:32 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> +	var/turf/target_turf = get_ranged_target_turf(target, get_dir(src, target))
Зачем?

2024-09-26 20:32 UTC, Helg2 approved these changes
Вроде норм, в ТМ

2024-10-05 05:50 UTC, merged