Tip of the Round, но по Русски
PMC-Unga-Marines/Unga-Marines pull request #494
Opened 2024-10-02 22:11 UTC by BasiaBelov

## `Основные изменения`

Переведены советы на раунд и приколы с печеньем с записками (оказывается, они есть в билде)

## `Как это улучшит игру`

Там и правда есть несколько хороших советов, которые даже для меня оказались открытием.

## `Ченджлог`

```
:cl:Basia
add: Советы теперь на Гойда-языке
/:cl:
```

2024-10-03 07:46 UTC, homexp13 commented
вот людям заняться нечем

2024-10-03 07:51 UTC, Helg2 commented
Подсказки для ХВХ можно просто удалить

2024-10-03 07:59 UTC, Helg2 commented on strings/tips/meta.txt
> +Иногда, один администратор под ником Нехочуха, будет делать всё, чтобы вы померли к чертям. Бейте его в ответ при первой же возможности.
Чё за высер

2024-10-03 08:00 UTC, Helg2 commented on strings/tips/meta.txt
> +Будучи ксеносом или морпехом, будьте внимательны к флангам, независимо от того, идет ли натиск хорошо или застопорился.
```suggestion
Будучи ксеносом или морпехом, следите за флангом, независимо от того, идет ли натиск хорошо или застопорился.
```

2024-10-03 08:05 UTC, homexp13 reviewed
Броня SOM лучше, чем броня морпехов, защищает от пуль, но хуже от лазеров, однако пули могут нанести длительные повреждения осколками, переломами и _**сучьями!**_
_**Боковое**_ оружие не является полным мусором. В очень сложной ситуации оно может спасти вам жизнь.
Морпех может взять с собой два _**двуручных**_ пистолета
Будучи инженером, вы можете разбирать баррикады из мешков с песком, используя **инструмент для рытья траншей.** _(универсальный инструмент)_
У вендоров есть вода. Оставайтесь с гидратированным запасом. (_**Спасибо переводчику)**_

перевод уровня инструментальный инструмент

2024-10-03 08:06 UTC, Helg2 commented on strings/tips/xeno.txt
> +Обмен плитками с морпехами через намерение помочь может привести к интересным последствиям.
```suggestion
Обмен местами с морпехами через намерение помочь может привести к интересным последствиям.
```

2024-10-03 08:06 UTC, homexp13 commented on strings/tips/meta.txt
> +Иногда, один администратор под ником Нехочуха, будет делать всё, чтобы вы померли к чертям. Бейте его в ответ при первой же возможности.
золото

2024-10-03 08:07 UTC, Helg2 commented on strings/tips/xeno.txt
> +Попадание в грудь может легко повредить печень, легкие или даже сердце.
```suggestion
Перелом головы - хорошая долгосрочная инвестиция, вызывающая у морпехов повреждение мозга.
Перелом груди может легко повредить печень, легкие или даже сердце.
```

2024-10-03 08:09 UTC, Helg2 commented on strings/tips/xeno.txt
> +Если вы Бойлер, древний Повелитель, Король или Королева, у вас есть самая едкая кислота для расплавления предметов.
```suggestion
Если вы Бойлер, древний Повелитель Улья, Король или Королева, у вас есть самая едкая кислота для расплавления предметов.
```

2024-10-03 08:09 UTC, Helg2 commented on strings/tips/xeno.txt
> +У Защитников и Шрики есть очень возможность сметать гранаты отправителям.
```suggestion
У Защитников и Шрики есть очень возможность откидывать гранаты назад их отправителям.
```

2024-10-03 08:11 UTC, Helg2 commented on strings/tips/xeno.txt
> +В роли Охотника у вас почти идеальная невидимость, если вы стоите на месте.
```suggestion
В роли Охотника у вас почти полная невидимость, если вы стоите на месте.
```

2024-10-03 08:13 UTC, Helg2 commented on strings/tips/xeno.txt
> +В качестве Дрона или Стража ваша разъедающая кислота очень слаба, но это лучше, чем ничего.
```suggestion
В качестве Дрона или Часового ваша разъедающая кислота очень слаба, но это лучше, чем ничего.
```
Звучит не шибко понятнее, но хотя бы интуитивнее

2024-10-03 08:14 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи ксеносом, белые сорняки помогают вам быстрее исцелиться, зелёные замедляют морпехов, а фиолетовые сорняки - это обычные сорняки. Отдыхайте на белых сорняках, чтобы быстрее вылечиться!
```suggestion
Будучи ксеносом, белая трава помогает вам быстрее исцелиться, зелёная замедляют морпехов, а фиолетовая трава - это обычная трава. Отдыхайте на белой траве, чтобы быстрее вылечиться!
```
Какие в пизду сорняки

2024-10-03 08:15 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи ксеносом, помните, что при введении нейротоксина возможна передозировка, которая быстро убьет морпеха.
```suggestion
```
У нас нету нейротоксина

2024-10-03 08:16 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи ксеносом, быстрее потушиться об кислотный колодец, чем кататься по земле, чтобы потушить огонь.
```suggestion
Будучи ксеносом, быстрее потушиться об кислотный колодец, чем кататься по земле, чтобы потушить огонь. Также колодцы помогают против липучих гранат.
```

2024-10-03 08:17 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи ксеносом, кислотные колодцы тушат огонь, а при уничтожении взрываются кислотным облаком. Создавать кислотные колодцы могут Королева, Шрика, Преторианцы, Бойлера и Повелители Улья.
```suggestion
Будучи ксеносом, кислотные колодцы тушат огонь, а при уничтожении взрываются кислотным облаком. Создавать кислотные колодцы могут Королева, Шрика, Преторианцы, Бойлера, Повелители Улья и даже Дроны.
```

2024-10-03 08:18 UTC, HeXo4yXeH commented on strings/tips/meta.txt
> +Иногда, один администратор под ником Нехочуха, будет делать всё, чтобы вы померли к чертям. Бейте его в ответ при первой же возможности.
О это же я!

2024-10-03 08:19 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи ксеносом, набрасываясь на баррикаду с колючей проволокой, вы отскакиваете от нее.
Не совсем правда

2024-10-03 08:22 UTC, Helg2 commented on strings/tips/marine.txt
> +Здесь есть базар оружия и тактики. Не бойтесь найти свою нишу!
```suggestion
Существует множество оружия и тактик. Не бойтесь найти свою нишу!
```

2024-10-03 08:23 UTC, Helg2 commented on strings/tips/marine.txt
> +Наниты часто не стоят того, чтобы ими рисковать.
```suggestion
Наниты часто не стоят своего риска.
```

2024-10-03 08:23 UTC, Helg2 commented on strings/tips/marine.txt
> +Иногда в медблоке может не хватать энергии. Чтобы избежать этого, крикните ближайшему инженеру, чтобы он починил термоядерные реакторы или заменил энергоячейку в БТРе медблока.
```suggestion
Иногда в медблоке может не хватать энергии. Чтобы избежать этого, крикните ближайшему инженеру, чтобы он починил термоядерные реакторы или заменил энергоячейку в АПЦ медблока.
```
Не в том смысл АПЦ

2024-10-03 08:24 UTC, Helg2 commented on strings/tips/marine.txt
> +Криоподы в медблоке исцеляют большинство видов повреждений, но не повреждение органов!
```suggestion
Криоподы в медблоке исцеляют большинство травм, но не повреждениея органов!
```

2024-10-03 08:25 UTC, Helg2 commented on strings/tips/marine.txt
> +Старайтесь не врезаться в санитаров. От этого может зависеть ваша жизнь.
```suggestion
Старайтесь не мешать санитарам. От них зависит ваша жизнь.
```

2024-10-03 08:25 UTC, Helg2 commented on strings/tips/marine.txt
> +Один рейф может стать фатальным для операции.
```suggestion
```
У нас нету врейта

2024-10-03 08:27 UTC, Helg2 commented on strings/tips/marine.txt
> +Шахтер без турели - сидячая утка.
```suggestion
Бур без турели - легкая добыча.
```

2024-10-03 08:27 UTC, Helg2 commented on strings/tips/marine.txt
> +Вы можете выполнить тактическую перезарядку, перетащив свежий магазин с пояса на оружие.
```suggestion
Вы можете выполнить тактическую перезарядку, нажав оружием по магазину.
```

2024-10-03 08:28 UTC, Helg2 commented on strings/tips/marine.txt
> +В шлем можно поместить крошечные предметы.
```suggestion
В шлем можно поместить крошечные предметы. Как и в сапоги.
```

2024-10-03 08:28 UTC, Helg2 commented on strings/tips/marine.txt
> +Батареи для энергетического оружия можно превратить в самодельные гранаты с помощью мультиинструмента.
```suggestion
Батареи для энергетического оружия можно превратить в самодельные гранаты с помощью мультитула.
```

2024-10-03 08:31 UTC, Helg2 commented on strings/tips/marine.txt
> +У вендоров есть вода. Оставайтесь с гидратированным запасом. (Спасибо переводчику)
```suggestion
У вендоров есть вода. Пейте воду.
```

2024-10-03 08:32 UTC, Helg2 commented on strings/tips/marine.txt
> +Тарп V1 (продается в Requisitions), накрывшись им, вы сольетесь с плиткой, на которой находитесь.
```suggestion
Тарп V1 (продается в Requisitions), накрывшись им, вы сольетесь с окружением, в котором находитесь.
```

2024-10-03 08:32 UTC, Helg2 commented on strings/tips/marine.txt
> +Броня B18 из «Реквизитов» имеет встроенную медицинскую систему. Система Valkyrie Automedical Armor System может сделать то же самое для других доспехов.
```suggestion
Броня Б18 из Карго имеет встроенную медицинскую систему. Система Valkyrie Automedical Armor System может сделать то же самое для других доспехов.
```

2024-10-03 08:33 UTC, Helg2 commented on strings/tips/marine.txt
> +Будучи санитаром или врачом, помните, что ваш HUD покажет вам, сколько времени осталось до дефибрилляции пациента. От максимума к минимуму: желтый, оранжевый и красный.
```suggestion
Будучи санитаром или врачом, помните, что ваш HUD покажет вам, сколько времени осталось до дефибрилляции пациента. От максимума к минимуму: зелёный, жёлтый и красный.
```

2024-10-03 08:34 UTC, Helg2 commented on strings/tips/marine.txt
> +Для инженера C4 дешевле, но детопакеты более универсальны.
```suggestion
Для инженера C4 дешевле, но детпакеты более универсальны.
```

2024-10-03 08:34 UTC, Helg2 commented on strings/tips/marine.txt
> +В качестве инженера детопакеты можно перевести в режим разрушения для создания взрывной ловушки.
```suggestion
В качестве инженера детпакеты можно перевести в режим разрушения для создания взрывной ловушки.
```

2024-10-03 08:34 UTC, Helg2 commented on strings/tips/marine.txt
> +В качестве инженера ремонтируйте шахтные колодцы. Эти шахтные машины будут добывать форон или платину, которые можно использовать в карго, зарабатывая тем самым больше очков!
```suggestion
В качестве инженера ремонтируйте буры. Буры будут добывать форон или платину, которые можно использовать в карго, зарабатывая тем самым больше очков!
```

2024-10-03 08:35 UTC, Helg2 commented on strings/tips/marine.txt
> +Будучи санитаром, носилки должны быть связаны с активным маяком, чтобы он мог телепортировать пациента.
```suggestion
Будучи санитаром, носилки для эвакуации должны быть связаны с активным маяком, чтобы он мог телепортировать пациента.
```

2024-10-03 08:35 UTC, Helg2 commented on strings/tips/marine.txt
> +Будучи врачом, вы имеете доступ к химическому аппарату. Экспериментируйте, чтобы найти лучшие лекарства.
```suggestion
Будучи врачом, вы имеете доступ к химическому раздатчику. Экспериментируйте, чтобы найти лучшие лекарства.
```

2024-10-03 08:36 UTC, Helg2 commented on strings/tips/marine.txt
> +Будучи врачом, наденьте белый жилет из тесьмы, который подходит к вашей спецодежде и в котором можно хранить хирургические инструменты.
```suggestion
Будучи врачом, наденьте белый хирургическую разгрузку, который подходит к вашей спецодежде и в котором можно хранить хирургические инструменты.
```

2024-10-03 08:37 UTC, Helg2 commented on strings/tips/marine.txt
> +Если вы врач, криотубы отлично справляются с основными повреждениями.
```suggestion
Если вы врач, криокамеры отлично справляются с основными повреждениями.
```

2024-10-03 08:37 UTC, Helg2 commented on strings/tips/marine.txt
> +Будучи врачом, криотрубки лечат внутренние кровотечения и переломы, хотя и медленно.
```suggestion
Будучи врачом, криокамеры лечат внутренние кровотечения и переломы, хотя и медленно.
```

2024-10-03 08:39 UTC, Helg2 commented on strings/tips/marine.txt
> +Морпех может взять с собой два двуручных пистолета - один в слоте костюма, другой на спине.
```suggestion
Морпех может взять с собой две двуручных пушки - одна в слоте костюма, другая на спине.
```

2024-10-03 08:39 UTC, Helg2 commented on strings/tips/marine.txt
> +В качестве морпеха вы можете получить навесное оборудование у торговцев оружием, обычно в ходе подготовки.
```suggestion
В качестве морпеха вы можете получить обвесы на оружие в вендорах, обычно в ходе подготовки.
```

2024-10-03 08:41 UTC, Helg2 commented on strings/tips/marine.txt
> +Если основной натиск застопорился и территория перегружена, попробуйте скоординироваться с несколькими другими и отправиться в другой район.
```suggestion
Если основной натиск застопорился и территория перегружена, попробуйте скоординироваться с другими морпехами и отправиться в другой район.
```

2024-10-03 08:42 UTC, Helg2 commented on strings/tips/marine.txt
> +Продвигаясь в район, проверяйте фланги. Особенно это касается пещер и закрытых помещений.
```suggestion
Продвигаясь, следите за флангами. Особенно в пещерах и закрытых помещениях.
```

2024-10-03 08:42 UTC, Helg2 commented on strings/tips/marine.txt
> +Смоляные конструкции слабее к ударам ближнего боя, чем к пулям. Доставайте свои ножи, мечи и штыки!
```suggestion
Большинство смоляных конструкций слабы к ударам ближнего боя. Доставайте свои ножи, мечи и штыки!
```

2024-10-03 08:43 UTC, Helg2 commented on strings/tips/marine.txt
> +По мере продвижения всегда очищайте от сорняков и чужих строений. Лабиринт из смолы вынуждает морпехов вступать в бой с ксеноморфами в режиме рукопашного боя, что снижает вашу выживаемость. Однако эт
```suggestion
По мере продвижения всегда очищайте от травы и чужих строений. Лабиринт из смолы вынуждает морпехов вступать в бой с ксеноморфами в режиме рукопашного боя, что снижает вашу выживаемость. Однако это повышает ваши шансы на спасение!
```

2024-10-03 08:43 UTC, Helg2 commented on strings/tips/marine.txt
> +Всегда проверяйте наличие ловушек под незакрепленными предметами на сорняках - это может спасти ваше лицо!
```suggestion
Всегда проверяйте наличие ловушек под незакрепленными предметами на траве - это может спасти ваше лицо!
```

2024-10-03 08:45 UTC, Helg2 commented on strings/tips/marine.txt
> +Если вы не морпех отряда, то у вас есть специальная комната в подготовке, где продается специальное снаряжение.
```suggestion
Если вы морпех, то у вас есть специальная комната в подготовке, где продается специальное снаряжение.
```

2024-10-03 08:45 UTC, Helg2 commented on strings/tips/marine.txt
> +Боковое оружие не является полным мусором. В очень сложной ситуации оно может спасти вам жизнь.
```suggestion
Вторичное оружие не является полным мусором. В сложной ситуации оно может спасти вам жизнь.
```

2024-10-03 08:48 UTC, Helg2 commented on strings/tips/marine.txt
> +Будучи морпехом отряда, вы можете приобрести у вендора излишков снаряжения отдельные элементы брони егерского образца и модули для боевого экзоскелета XM-02. В конце концов, это модульное снаряжение.
```suggestion
Будучи морпехом отряда, вы можете приобрести в вендоре с бронёй отдельные элементы брони егерского образца и модули для боевого экзоскелета XM-02. В конце концов, это модульное снаряжение.
```

2024-10-03 08:49 UTC, Helg2 commented on strings/tips/marine.txt
> +Будучи морпехом, старайтесь не целиться в голову. Это выгодно ксеноморфам, так как они не получат больше урона по голове, а при дружественном обстреле вы можете проломить им голову. Цельтесь в центр
```suggestion
Будучи морпехом, старайтесь не целиться в голову. Это выгодно ксеноморфам, так как они не получат больше урона по голове, а при дружественном огне вы можете сломать им голову. Цельтесь в центр массы!
```

2024-10-03 08:49 UTC, Helg2 commented on strings/tips/marine.txt
> +В морпехе вы можете использовать двойное оружие, чтобы стрелять из обоих одновременно. Однако при этом увеличивается разброс и снижается точность.
```suggestion
Вы можете использовать двойное оружие, чтобы стрелять из обоих одновременно. Однако при этом увеличивается разброс и снижается точность.
```

2024-10-03 08:50 UTC, Helg2 commented on strings/tips/marine.txt
> +Будучи морпехом, произнесите «*medic», чтобы вызвать медицинскую помощь. Вы можете привязать это к клавишам в игровых настройках.
```suggestion
Будучи морпехом, произнесите «*medic», чтобы позвать медика. Вы можете привязать это к клавишам в игровых настройках.
```

2024-10-03 08:51 UTC, Helg2 commented on strings/tips/marine.txt
> +Во время самоуничтожения зеленые стержни управления становятся вооруженными стержнями управления. Каждый стержень поднимается за 3 минуты, что заставляет морпехов удерживать «Самоуничтожение» в течен
Кринж

2024-10-03 08:51 UTC, Helg2 commented on strings/tips/marine.txt
> +Зелёные сорняки и фиолетовая липкая смола замедляют вас. Избавьтесь от них!
```suggestion
Зелёная трава и фиолетовая липкая смола замедляют вас. Избавьтесь от них!
```

2024-10-21 18:40 UTC, BasiaBelov commented
Прошёлся глазами ПО ВСЕМ советам и исправил тупые выражения на более понятные человеческие.

2024-10-23 08:57 UTC, Helg2 commented on strings/tips/meme.txt
> +Совет: Стань лучше.
```suggestion
Совет: Научись играть.
```

2024-10-23 08:57 UTC, Helg2 commented on strings/tips/meme.txt
> +Совет: Смерть - это проблемы с навыком.
```suggestion
Совет: Смерть - это симптом проблем с навыком.
```

2024-10-23 08:57 UTC, Helg2 commented on strings/tips/meta.txt
> +Иногда, один администратор под ником Нехочуха, будет делать всё, чтобы вы померли к чертям. Бейте его в ответ при первой же возможности.
В мемы перемести.

2024-10-23 08:57 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи ксеносом, помните, что при введении нейротоксина возможна передозировка, которая быстро убьет морпеха.
Все еще нету нейротоксина.

2024-10-23 08:57 UTC, Helg2 commented on strings/tips/xeno.txt
> +Опытные Осквернители могут легко убить любого морпеха за считанные секунды.
```suggestion
Опытные Дефайлеры могут легко убить любого морпеха за считанные секунды.
```

2024-10-23 08:57 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи Дроном, Хивлордом, Хивмайдом, Шрикой или Королевой, будьте умны со своими стенами. Постарайтесь обеспечить как можно больше свободного движения для своей команды.
```suggestion
Для Дрона, Хайвлорда, Хайвмайнда, Шрики и Королевы большой лабиринт - почти всегда хорошее вложение средств. Правда если у морпехов не достанется мозгов запустить ОБ...
Будучи Дроном, Хайвлордом, Хайвмайндом, Шрикой или Королевой, умно распоряжайтесь своими стенами. Постарайтесь обеспечить как можно больше свободного движения для своей команды.
```

2024-10-23 08:57 UTC, Helg2 commented on strings/tips/xeno.txt
> +У Бойлера, примо Хивлорда, Короля и Королевы - самая едкая кислота для расплавления всякого.
```suggestion
У Бойлера, примо Хайвлорда, Короля и Королевы - самая едкая кислота для расплавления всякого.
```

2024-10-23 08:57 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи Ревагером или Королевой, вы устойчивы к огню, но не огнеупорны. Вас все еще можно поджечь, но вы получаете очень мало урона. А вот уже Король, огнеупорен, но до тех пор, пока его броня не буде
```suggestion
Будучи Равагером или Королевой, вы устойчивы к огню, но не огнеупорны. Вас все еще можно поджечь, но вы получаете очень мало урона. А вот уже Король, огнеупорен, но до тех пор, пока его броня не будет повреждена.
```

2024-10-23 08:57 UTC, Helg2 commented on strings/tips/xeno.txt
> +Прежде чем эволюционировать в ХивМайнд в роли Дрона, спрячьтесь в безопасном месте! Когда вы эволюционируете, вы создадите ядро, которое нельзя будет сдвинуть с места.
```suggestion
Прежде чем эволюционировать в ХайвМайнд в роли Дрона, спрячьтесь в безопасном месте! Когда вы эволюционируете, вы создадите ядро, которое нельзя будет сдвинуть с места.
```

2024-10-23 08:57 UTC, Helg2 commented on strings/tips/xeno.txt
> +Хороший Дефуня - один из лучших способов задержать натиск.
```suggestion
Хороший Дефендер - один из лучших способов задержать натиск.
```

2024-10-23 08:57 UTC, Helg2 commented on strings/tips/marine.txt
> +У вендоров есть вода. Оставайтесь с гидратированным запасом. (Спасибо переводчику)
Все еще кринж.

2024-10-24 00:55 UTC, BasiaBelov commented on strings/tips/meme.txt
> +Совет: Смерть - это проблемы с навыком.
Чёта не звучит.

2024-10-25 21:03 UTC, Tatarla requested changes

2024-10-25 21:03 UTC, Tatarla commented on strings/tips/meta.txt
> +Если вы мертвы и вы хотите завладеть мобом, завладейте им прямо сейчас! Всё слева-сверху.
Если вы мертвы и вы хотите поиграть за Т0 касты ксеноморфов или ССД-игроков, то сделайте это прямо сейчас! Будучи в госте изучите кнопки в верхнем левом углу экрана.

2024-10-25 21:03 UTC, Tatarla commented on strings/tips/xeno.txt
> +Будучи ксеносом, вы можете спокойно плавить баррикады, находясь газе Осквернителя или Бойлера, если только сможете кликнуть в нужную точку. В газе также очень удобно прятаться, чтобы устраивать засад
Оксернителя поменяй на буквальный перевод. Как Бойлер = бойлер.

2024-10-25 21:03 UTC, Tatarla commented on strings/tips/xeno.txt
> +Будучи Личинкой, вы можете проскользнуть под незакрепленными и несваренными дверями, щелкнув по ним.
Личинку на лярву по всему тексту

2024-10-25 21:03 UTC, Tatarla commented on strings/tips/xeno.txt
> +В качестве Дрона или Стрелка ваша разъедающая кислота очень слаба, но это лучше, чем ничего.
Стрелка на ээ... Это либо сент, либо спитак? На того, кого изначально задумано.

2024-10-25 21:03 UTC, Tatarla commented on strings/tips/xeno.txt
> +Будучи Плевальщиком, Бойлером, Преторианцем или Королевой, пользуйтесь неохраняемыми баррикадами и защитными сооружениями; плавьте их или постоянно плюйтесь кислотой, если можете.
Плевальщика на спиттера

2024-10-30 06:43 UTC, Helg2 commented on strings/tips/marine.txt
> +Раскидка сигнальных фонарей может быть невероятно полезным, особенно когда король использует способность тушить фонари. Многие морпехи не видят в темноте, поэтому если осветить сигнальными фонарями п
Насрал, "сигнальные ракеты" подходили лучше.

2024-10-30 14:28 UTC, BasiaBelov commented on strings/tips/xeno.txt
> +Будучи ксеносом, вы можете спокойно плавить баррикады, находясь газе Дефилера или Бойлера, если только сможете кликнуть в нужную точку. В газе также очень удобно прятаться, чтобы устраивать засады та
Даже звучит кринжово, "Дефайлер"...

2024-11-03 10:59 UTC, Tatarla requested changes

2024-11-03 10:59 UTC, Tatarla commented on strings/tips/xeno.txt
> +Самые сильные феромоны у Короля, за ним следуют Королева, Преторианцы, Разум Улья, Шрика, чуть слабее у Повелителей Ульев, Осквернителей и Носителей. У Дронов самые слабые феромоны.
Хайвмайнд

2024-11-03 10:59 UTC, Tatarla commented on strings/tips/xeno.txt
> +Самые сильные феромоны у Короля, за ним следуют Королева, Преторианцы, Разум Улья, Шрика, чуть слабее у Повелителей Ульев, Осквернителей и Носителей. У Дронов самые слабые феромоны.
Хайрдорд вместо повелителей улья
Дефайлер вместо осквернителя
Керриер вместо носителя

2024-11-03 10:59 UTC, Tatarla commented on strings/tips/xeno.txt
> +В роли Руни, Варлока или Лярвой вы можете проходить через оконные рамы, не забираясь на них предварительно.
Лярвы

2024-11-03 10:59 UTC, Tatarla commented on strings/tips/xeno.txt
> +У Дефуни и Шрики есть возможность откидывать гранаты назад их отправителям.
Дефендера

2024-11-03 18:08 UTC, Helg2 commented on strings/tips/xeno.txt
> +Самые сильные феромоны у Короля, за ним следуют Королева, Преторианцы, Хивмайнд, Шрика, чуть слабее у Хивлорда, Дефайлеров и Керриеов. У Дронов самые слабые феромоны.
```suggestion
Будучи ксеносом, кислотные колодцы тушат огонь, а при уничтожении взрываются кислотным облаком. Создавать кислотные колодцы могут Королева, Шрика, Преторианцы, Бойлера, Хайвлорды и даже Дроны.
Королева, Король, Шрика и Хайвмайнд имеют доступ к «Благословению королевы» - меню, позволяющее улью использовать пси-очки, чтобы дать ксеноморфам преимущество на поле боя.
Если у вас есть кислотный плевок, вы можете плюнуть в бак с горючим для сварки, чтобы взорвать его. Если сварочное топливо находится рядом с врагами, вы можете устроить им приятный сюрприз!
Будучи ксеносом, часто проверяйте состояние улья. Возможно, у вас давно проблемы в тылу...
Некоторые ксеносы обладают феромонами, которые могут помочь улью. Frenzy увеличивает скорость, Warding - броню, а Recovery - исцеление.
Самые сильные феромоны у Короля, за ним следуют Королева, Преторианцы, Хайвмайнд, Шрика, чуть слабее у Хайвлорда, Дефайлеров и Керриеов. У Дронов самые слабые феромоны.
```

2024-11-03 18:08 UTC, Helg2 commented on strings/tips/xeno.txt
> +Хивмайнд очень искусен в обходе морпехов с фланга. Дождитесь, когда они начнут наступать, и закройте их сзади!
```suggestion
Хайвмайнд очень искусен в обходе морпехов с фланга. Дождитесь, когда они начнут наступать, и закройте их сзади!
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи ксеносом, вы можете спокойно плавить баррикады, находясь газе Дефайлера или Бойлера, если только сможете кликнуть в нужную точку. В газе также очень удобно прятаться, чтобы устраивать засады т
```suggestion
Будучи ксеносом, вы можете спокойно плавить баррикады, находясь в газе Дефайлера или Бойлера, если только сможете кликнуть в нужную точку. В газе также очень удобно прятаться, чтобы устраивать засады так, чтобы морпехи не заметили вас.
```
Насрал

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи ксеносом, кислотные колодцы тушат огонь, а при уничтожении взрываются кислотным облаком. Создавать кислотные колодцы могут Королева, Шрика, Преторианцы, Бойлера, Хайвлорды и даже Дроны.
```suggestion
Будучи ксеносом, кислотные колодцы тушат огонь, а при уничтожении взрываются кислотным облаком. Создавать кислотные колодцы могут Королева, Шрика, Преторианцы, Бойлеры, Хайвлорды и даже Дроны.
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Королева, Король, Шрика и Хайвмайнд имеют доступ к «Благословению королевы» - меню, позволяющее улью использовать пси-очки, чтобы дать ксеноморфам преимущество на поле боя.
```suggestion
Королева, Король, Шрика, Хайвмайнд и Хайвлорд имеют доступ к «Благословению королевы» - меню, позволяющее улью использовать пси-очки, чтобы дать ксеноморфам преимущество на поле боя.
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Если у вас есть кислотный плевок, вы можете плюнуть в бак с горючим для сварки, чтобы взорвать его. Если сварочное топливо находится рядом с врагами, вы можете устроить им приятный сюрприз!
```suggestion
Если у вас есть кислотный плевок, вы можете плюнуть в бак с горючим для сварки, чтобы взорвать его. Если бак со сварочным топливом находится рядом с врагами, вы можете устроить им приятный сюрприз!
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Самые сильные феромоны у Короля, за ним следуют Королева, Преторианцы, Хайвмайнд, Шрика, чуть слабее у Хайвлорда, Дефайлеров и Керриеов. У Дронов самые слабые феромоны.
```suggestion
Самые сильные феромоны у Короля, за ним следуют Королева, Преторианцы, Шрика, чуть слабее у Хайвмайнда, Хайвлорда, Дефайлеров и Керриеров. У Дронов самые слабые феромоны.
```
У шрики/претора 4.5 у Хм-а 4.

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи ксеносом, вы можете проползать через дыры в стенах, сделанные кислотой, щелкнув на них специальным щелчком (по умолчанию: CTRL+щелчок) или протащив себя по ним. Если вы слишком велики, чтобы п
```suggestion
Будучи ксеносом, вы можете пролезать через дыры в стенах, сделанные кислотой, нажав по ним специальным щелчком (по умолчанию: Ctrl-ЛКМ) , или же перетащив себя на них. Если вы слишком велики, чтобы пролезть, то вместо этого вы сломаете стену.
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи ксеносом, вы можете перелезать через оконные рамы, прыгая (по умолчанию: пробел), нажимая на них специальным щелчком (по умолчанию: CTRL+клик) или перетаскивая себя на них.
```suggestion
Будучи ксеносом, вы можете перепрыгнуть (по умолчанию: Space) или перелезть через оконные рамы, нажав на них специальным щелчком (по умолчанию: CTRL-ЛКМ) или перетащив себя на них.
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Бойлер начинает светиться тем сильнее, чем больше у него снарядов.
```suggestion
Бойлер начинает светиться тем сильнее, чем больше у него снарядов. Но вместе с этим время перезарядки выстрела уменьшается.
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи ксеносом, не преграждайте путь другим ксеносам, когда они отступают. Чтобы обойти это, можно воспользоваться намерением помочь или просто отойти с дороги.
```suggestion
Будучи ксеносом, не преграждайте путь другим ксеносам, когда они отступают. Чтобы предотвратить это, можно использовать зеленый интент или просто отойти с дороги.
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи ксеносом, белая трава помогает вам быстрее исцелиться, зелёная замедляют морпехов, а фиолетовая трава - это обычная трава. Отдыхайте на белой траве, чтобы быстрее вылечиться!
```suggestion
Будучи ксеносом, белая трава помогает вам быстрее исцелиться, зелёная замедляет морпехов, а фиолетовая трава - это обычная трава. Отдыхайте на белой траве, чтобы быстрее вылечиться!
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи Лярвой, вы можете проскользнуть под незакрепленными и несваренными дверями, щелкнув по ним.
```suggestion
Будучи Лярвой, вы можете проскользнуть под незакрепленными и незаваренными дверями, щелкнув по ним.
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи Лярвой, во время роста оставайтесь на траве. В результате вы будете расти быстрее.
```suggestion
Будучи Лярвой, во время роста оставайтесь на траве. Так вы будете расти быстрее.
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +В роли Руни, Варлока или Лярвы вы можете проходить через оконные рамы, не забираясь на них предварительно.
```suggestion
В роли Руни, Пантеры, Варлока или Лярвы вы можете проходить через оконные рамы, не забираясь на них предварительно.
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Обмен местами с морпехами через намерение помощи может привести к интересным последствиям.
```suggestion
Обмен местами с морпехами через зеленый интент может привести к интересным последствиям.
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Хайвмайнд очень искусен в обходе морпехов с фланга. Дождитесь, когда они начнут наступать, и закройте их сзади!
```suggestion
Хайвмайнд очень искусен в обходе морпехов с фланга. Дождитесь, когда они начнут наступать, и застройте их сзади!
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи Хантером, движение вашего Миража зависит от вашего намерения, вроде как...
```suggestion
Будучи Хантером, движение ваших копий зависит от вашего интента, в зеленом они будут отступать, в красном же будут атаковать. 
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Для Дрона, Хайвлорда, Хайвмайнда, Шрики и Королевы большой лабиринт - почти всегда хорошее вложение средств. Правда если у морпехов не достанется мозгов запустить ОБ...
```suggestion
Для Дрона, Хайвлорда, Хайвмайнда, Шрики и Королевы большой лабиринт - почти всегда хорошее вложение средств. Но только если морпехам не хватит мозгов запустить ОБ...
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Прежде чем эволюционировать в Хайвмайнд  в роли Дрона, спрячьтесь в безопасном месте! Когда вы эволюционируете, вы создадите ядро, которое нельзя будет сдвинуть с места.
```suggestion
Прежде чем эволюционировать в Хайвмайнда, спрячьтесь в безопасном месте! Когда вы эволюционируете, вы создадите ядро, которое нельзя будет сдвинуть с места.
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи Равагером  или Королевой, вы устойчивы к огню, но не огнеупорны. Вас все еще можно поджечь, но вы получаете очень мало урона. А вот уже Король, огнеупорен, но до тех пор, пока его броня не буд
```suggestion
Будучи Равагером или Королевой, вы устойчивы к огню, но не огнеупорны. Вас все еще можно поджечь, но вы получаете очень мало урона. А вот уже Король, огнеупорен, но до тех пор, пока его броня не будет повреждена.
```

2024-11-04 10:29 UTC, Helg2 commented on strings/tips/xeno.txt
> +Будучи Шрикой, воспользуйтесь своими экстрасенсорными способностями. Используйте Psychic Fling и Unrelenting Force, чтобы сместить морпеха или даже подтолкнуть определенные и опасные предметы к врага
```suggestion
Будучи Шрикой, пользуйтесь своими экстрасенсорными способностями. Используйте Psychic Fling и Unrelenting Force, чтобы сместить морпеха или даже подтолкнуть определенные и опасные предметы к врагам и наоборот.
```

2024-11-04 17:45 UTC, Helg2 commented on strings/tips/meta.txt
> +Если вы живы, используйте команду «сопротивляться» (по умолчанию: B), чтобы остановиться, упасть и перекатиться во время возгарания. Люди также могут использовать команду «сопротивляться», чтобы вырв
```suggestion
Если вы горите, используйте команду «Resist» (по умолчанию: B), чтобы остановиться, упасть и перекатиться. Люди также могут использовать команду «Resist», чтобы вырваться из захвата Вариора или просто отстегнуться от стула.
```

2024-11-04 17:45 UTC, Helg2 commented on strings/tips/meta.txt
> +Будучи морпехом или ксеносом, вы умрете быстро и ужасно, если окажетесь в среде без давления (она же - спасе).
```suggestion
Будучи морпехом или ксеносом, вы умрете быстро и ужасно, если окажетесь в среде без давления (она же - космос).
```

2024-11-04 17:45 UTC, Helg2 commented on strings/tips/meme.txt
> +Совет: Все крутые ребята принимают боевые стимуляторы.
```suggestion
Совет: Победители не используют наниты.
Совет: Все крутые ребята используют боевые стимуляторы.
```
Так наверное получше.

2024-11-04 17:45 UTC, Helg2 commented on strings/tips/meme.txt
> +Мотыльки существуют, а правительство их скрывает.
```suggestion
Люди-мотыльки существуют, а правительство их скрывает.
```

2024-11-04 17:45 UTC, Helg2 commented on strings/tips/meme.txt
> +Правительство - это просто миф, созданный мотыльками.
```suggestion
Правительство - это просто миф, созданный людьми-мотыльками.
```

2024-11-04 17:45 UTC, Helg2 commented on strings/tips/meme.txt
> +Инженстан - это маленькое государство, что никак не может укрепиться на одном месте. Скорее всего, Артём делает что-то не так...
```suggestion
Инжестан - это маленькое государство, что никак не может укрепиться на одном месте. Скорее всего, Артём делает что-то не так...
```

2024-11-05 11:01 UTC, Helg2 commented on strings/tips/marine.txt
> +Будучи инженером, ремонтируйте буры. Буры будут добывать форон или платину, которые можно использовать в карго, зарабатывая тем самым больше очков!
```suggestion
Будучи инженером, ремонтируйте буры. Буры будут добывать форон или платину, которые можно продать в карго, зарабатывая тем самым больше очков!
```

2024-11-05 11:02 UTC, Helg2 commented on strings/tips/marine.txt
> +Криокамеры отлично справляются с основными повреждениями. Также они лечат внутренние кровотечения и переломы но медленно медленно.
```suggestion
Криокамеры отлично справляются с основными повреждениями. Также они медленно лечат внутренние кровотечения и переломы.
```

2024-11-05 11:02 UTC, Helg2 commented on strings/tips/marine.txt
> +В качестве морпеха вы сможете обращаться со всеми видами оружия, представленными в игре. Ну, как минимум, это говорят цифры...
```suggestion
Будучи морпехом вы можете обращаться почти со всеми видами оружия, представленными в игре.
```

2024-11-05 11:04 UTC, Helg2 commented on strings/tips/marine.txt
> +Будучи морпехом, старайтесь не целиться в голову. Это выгодно ксеноморфам, так как они не получат больше урона по голове, а при дружественном огне вы можете сломать им череп. Цельтесь в центр массы!
```suggestion
Будучи морпехом, старайтесь не целиться в голову. Ксеноморфы не получают больше урона по голове, а при дружественном огне вы можете сломать своим союзникам череп. Цельтесь в центр массы!
```

2024-11-05 11:09 UTC, Helg2 commented on strings/tips/marine.txt
> +Если граната M40 FLDP при броске столкнется с любым мобом, он загорится. Будьте осторожны, бросая флаера.
```suggestion
Если флаер M40 FLDP при броске столкнется с любым мобом, он загорится. Будьте осторожны, бросая флаера.
```

2024-11-05 11:10 UTC, Helg2 commented on strings/tips/marine.txt
> +Вы можете снять с боевого экзоскелета XM-02 части брони (части ног, части рук и части груди) и модули брони (Валькирия, Балдур и т. д.), нажав Alt+клик по экзоскелету.
```suggestion
Вы можете снять с боевого экзоскелета XM-02 части брони (части ног, части рук и части груди) и модули брони (Валькирия, Балдур и т. д.), нажав Alt+ЛКМ по экзоскелету.
```

2024-11-05 11:11 UTC, Helg2 commented on strings/tips/marine.txt
> +Будучи морпехом, вы можете перебираться через препятствия высотой по пояс, такие как мешки с песком, оконные рамы или столы, нажимая на них «специальным щелчком» (по умолчанию: CTRL+клик) или перетас
```suggestion
Будучи морпехом, вы можете перебираться через препятствия высотой по пояс, такие как мешки с песком, оконные рамы или столы, нажимая на них «специальным щелчком» (по умолчанию: CTRL+ЛКМ) или перетаскивая себя на них.
```

2024-11-05 11:12 UTC, Helg2 commented on strings/tips/marine.txt
> +В Карго есть множество предметов для повышения боевой мощи морпехов: навесное оборудование, боеприпасы и другие игрушки; спросите у их команды, что есть в наличии, и вы можете быть приятно удивлены.
```suggestion
В Карго есть множество предметов для повышения боевой мощи морпехов: навесное оборудование, боеприпасы и другие игрушки. Спросите у сотрудников карго, что есть в наличии, и вы можете быть приятно удивлены. Наличие дополнительных приспособлений зависит от поставок.
```

2024-11-05 11:13 UTC, Helg2 commented on strings/tips/marine.txt
> +Удаление сорняков за морпеха означает, что ксеноморфы не смогут воспользоваться преимуществами поля боя. Для этого отлично подходит ваш стандартный сапожный нож.
```suggestion
Удаление травы ксеноморфов за морпеха означает, что они не смогут воспользоваться преимуществами поля боя. Для этого отлично подходит ваш стандартный сапожный нож.
```

2024-11-05 11:18 UTC, Helg2 commented on strings/tips/marine.txt
> +По мере продвижения всегда очищайте от травы и чужих строений. Лабиринт из смолы вынуждает морпехов вступать в бой с ксеноморфами в режиме рукопашного боя, что снижает вашу выживаемость. Однако это п
```suggestion
По мере продвижения всегда очищайте траву и строения ксеноморфов. Лабиринт из смолы вынуждает морпехов вступать в бой с ксеноморфами в ближнем бою, что снижает вашу выживаемость.
```

2024-11-05 11:18 UTC, Helg2 commented on strings/tips/marine.txt
> +Еще ни один раунд не был выигран за баррикадой сказал бы я. Инженстан - это долгая, скучная, но победа, наверно...
```suggestion
Еще ни один раунд не был выигран за баррикадой, сказал бы я. Инжестан - это долгая, скучная, но победа. Наверное...
```

2024-11-07 11:06 UTC, Helg2 commented on strings/tips/meme.txt
> +Правительство - это просто миф, созданный молью.
```suggestion
Правительство - это просто миф, созданный молями.
```

2024-11-07 11:08 UTC, Helg2 approved these changes

2024-11-07 11:08 UTC, merged