Buff sg
PMC-Unga-Marines/Unga-Marines pull request #542
Opened 2024-10-13 10:29 UTC by Tatarla

## `Основные изменения`
1. СГ29 18 урона 15 ап > 20 урона 25 ап
Стандартный сг. Без особых требований и проблем. Так называемый "золотой стандарт"
2. СГ85 10 урона 25 ап > 50 урона -20 ап
Огромный боезапас, высокий урон по небронированным целям.
3. СГ25 17.5 урона 10 ап > 25 урона 35 ап
Пониженный боезапас, штурмовое оружие, высокий расход боеприпасов. Компенсируется повышенным уроном и ап.
## `Как это улучшит игру`
СГ сейчас значительно хуже, чем основные пушки, из-за чего смартганеры объективно неиграбельны.
Данный ПР исправляет ситуацию.

## `Ченджлог`

```
:cl:
balance: СГ29 18 урона 15 ап > 20 урона 25 ап
balance: СГ85 10 урона 25 ап > 50 урона -20 ап
balance: СГ25 17.5 урона 10 ап > 25 урона 35 ап
/:cl:
```

2024-10-13 10:58 UTC, Helg2 requested changes
Additional_xeno_penetration не забудь изменить

2024-10-13 11:19 UTC, Ghostkokos commented
А зачем СГ 85 делать пушкой для убийства руннеров варлоков и горгера если это по своей механике ствол чисто для подавленного огня с нанесением малейшего но урона

2024-10-13 11:20 UTC, Tatarla commented
> А зачем СГ 85 делать пушкой для убийства руннеров варлоков и горгера если это по своей механике ствол чисто для подавленного огня с нанесением малейшего но урона
Он все еще выполняет эти функции.

2024-10-13 17:22 UTC, CheBokJam commented
СГ85 перебаффан, если не сказать вообще проклят - сейчас он сносит любого, кто имеет меньше 70 буллет защиты за секунды. Верни старый СГ85 и отталкивайся от его изначальной идеи - много пуль, мало урона, сандеринг (понижение защиты на время)

2024-10-13 17:53 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/machinegun.dm
> +	additional_xeno_penetration = 0
```suggestion
```

2024-10-13 17:53 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/machinegun.dm
> +	damage = 50
25 ему думаю хватит за глаза

2024-10-14 22:11 UTC, Helg2 reviewed
С учётом доп ксено ап, у сг25 55 ап, что будет ебать чуть ли не все касты в игре, ты уверен на счёт этого?

2024-10-15 15:25 UTC, LoneAsket commented
Инцидент Равагера, только от лица СГ. Неплохо, неплохо.

2024-10-18 17:19 UTC, Helg2 requested changes
Т25 столько ап не нужно

2024-10-27 10:46 UTC, Helg2 requested changes
55 ар на сг25 все ще жирно
Изменения сг62 в ченжлог

2024-11-01 14:18 UTC, merged