Adds some limitations to acid blood splashes.
PMC-Unga-Marines/Unga-Marines pull request #544
Opened 2024-10-14 12:04 UTC by Helg2

## `Основные изменения`
Кислотные брызги теперь не появляются от бурн урона.
Если тело мертво, то шанс на брызг урезается в 2 раза.
Биттлы, Мантисы и Хаггеры теперь не обладают трейтом кислотной крови.

Убрал возможность доп ренжа у кислотной крови.
Добавил проверку на доступность цели перед нанесением урона (через стены больше не бьет).

Немного почистил код.

## `Как это улучшит игру`
Проверка на бурн урон добавит лазерам возможность стрелять в упор без урона, что сделает их чуть привлекательнее в глазах маринов. С точки зрения дизайна, бурн урон прижигает рану, поэтому никаких брызг.
Урезание шанса при мёртвом теле чтобы мары могли бить трупы чуть спокойнее. С точки зрения дизайна, давление в мёртвом теле в разы меньше чем в живом, поэтому брызг крови меньше.

## `Ченджлог`

```
:cl:
balance: Кислотные брызги теперь не появляются от бурн урона.
balance: Шанс на кислотные брызги из мертвых тел теперь ниже в 2 раза.
balance: Мантисы, битлы и хаггеры теперь не имеют трейт кислотной крови.
fix: Кислотные брызги теперь не наносят урон через стены.
/:cl:
```

2024-10-14 12:32 UTC, Tatarla approved these changes

2024-10-15 11:26 UTC, homexp13 requested changes

2024-10-15 11:26 UTC, homexp13 commented on code/modules/mob/living/carbon/xenomorph/damage_procs.dm
>  		check_blood_splash(damage, damagetype, 0, 1, sharp, edge)
радиус убери

2024-10-15 11:43 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/damage_procs.dm
>  		check_blood_splash(damage, damagetype, 0, 1, sharp, edge)
Ты про что?

2024-10-15 12:22 UTC, homexp13 commented on code/modules/mob/living/carbon/xenomorph/damage_procs.dm
>  		check_blood_splash(damage, damagetype, 0, 1, sharp, edge)
check_blood_splash(damage, damagetype, 0, 1, sharp, edge)

/mob/living/carbon/xenomorph/proc/check_blood_splash(damage = 0, damtype = BRUTE, chancemod = 0, sharp = FALSE, edge = FALSE)

в проке 5 параметров а при вызове 6, если я правильно понимаю 1 это был радиус и ты его не убрал при вызове прока, а в самом проке убрал

2024-10-15 12:28 UTC, homexp13 approved these changes

2024-10-16 03:46 UTC, merged