Adds delay for powerpacks and packet filling.
PMC-Unga-Marines/Unga-Marines pull request #547
Opened 2024-10-14 15:09 UTC by Helg2

## `Основные изменения`
У паверпаков для минигана и лазерок теперь есть задержка в 0.5 секунд перед подключением.
У коробок с патронами теперь есть задержка в 0.75 секунд перед заполнением магазина.

## `Как это улучшит игру`
У паверпаков и коробок с патронами должен быть минимальный минус в виде громоздкости, иначе резон использовать обычные магазины пропадает.

## `Ченджлог`

```
:cl:
balance: Паверпаки теперь имеют задержку в 0.5 секунд перед подключением.
balance: Коробки с патронами теперь имеют задержку перед пополнением в 0.75 секунд.
/:cl:
```

2024-10-15 09:29 UTC, Tatarla requested changes
Паверпаки заебись
Диджей под коробки хуйня, люди и так платят за них тем, что они занимают больше места, как и самим дрочем по заполнению пустых магазинов + микроменеджментом этих магазинов

2024-10-15 09:41 UTC, Helg2 commented
> Диджей под коробки хуйня, люди и так платят за них тем, что они занимают больше места, как и самим дрочем по заполнению пустых магазинов + микроменеджментом этих магазинов

На обычных игроках это почти никак не отобразиться, это скорее против тех кто носит лишь один магазин и в 3 клика перезаряжает его посреди боя.

2024-10-15 11:24 UTC, Tatarla commented
> > Диджей под коробки хуйня, люди и так платят за них тем, что они занимают больше места, как и самим дрочем по заполнению пустых магазинов + микроменеджментом этих магазинов
> 
> На обычных игроках это почти никак не отобразиться, это скорее против тех кто носит лишь один магазин и в 3 клика перезаряжает его посреди боя.

Как раз отразится, т.к им придется тратить больше времени на перезарядку. А они и так платят за неё местом в инвентаре.
Те, кто реально шарят, носят с собой два ящика с магазинами и в хуй не дуют с этой еблей магазинами и перезарядкой, имхо

2024-10-15 12:25 UTC, Helg2 commented
То что коробки занимают место - не является аргументом, так как во-первых некоторые магазины занимают столько же места, во-вторых занимают место как раз таки что от них ЕСТЬ польза, и этот пр никак не повлияет на сам менеджмент ресурсов маринами.
Самим ящикам наверное также стоит добавить замедление, чтобы выбор хотя был равноценным.

2024-10-15 15:19 UTC, LoneAsket commented
Плюс, кмк, Хельг забыл, что блядь с новой метой игровой и крутым балансом, единственная возможность маров побегать в отрыве от унгаболла и не сдохнуть/не слить катку - это выебать ксеносов, после чего те как твари разбегутся по карте.
А пока этого не произошло унгаболл нихуя не быстробегающий, а скорее похож на ебучую черепаху, которая пытается пересилить противоположное течение реки.

2024-10-15 16:36 UTC, Istrelok2107 commented
Все что имеет паверпак теперь можно станить постоянно и он будет мясом для битья. Сомнительно???
Коробки не стоит трогать либо делать максимальный дилей в 0.35

2024-10-16 06:51 UTC, ChromosomeKiller commented
Миниганы в жизни обратно не подключишь в бою, круто, тебя будут постоянно свапать или дергать, ставлю 10 из 10 довольных ксено

2024-10-18 04:47 UTC, closed without merging