Rebalance xeno HP and armor
PMC-Unga-Marines/Unga-Marines pull request #594
Opened 2024-10-22 16:34 UTC by Tatarla

## `Основные изменения`
Изменил статы ХП и/или армора у большей части каст.

## `Как это улучшит игру`
Более явное разделение на беносов, против которых вариативно использование ХП/АП патронов.
Повышение выживаемости и/или играбельности танков.
Повышение играбельности лазерок.

## `Ченджлог`
```
:cl:
balance: Бегемот получил 12 харда от буллета, потерял хард от мили, снижен хард от лазеров с 12 до 6
balance: Крашеру поднято ХП с 400 до 500, понерфлен софтармор от мили с 80 до 50, лазеры с 80 до 65
balance: Дефендеру поднято ХП с 320 до 410, получил хардармор 10 от буллета
balance: Претору поднято ХП с 460 до 570, снижен софтармор буллета с 50 до 25, лазеров с 50 до 15
balance: Сентинелю поднято ХП с 300 до 400
balance: Спиттеру поднято ХП с 310 до 450, софтармор буллета снижен с 35 до 20, лазеров с 35 до 10
/:cl:
```

2024-10-23 02:43 UTC, Qwadrob commented
Ребаланс хп и брони. Повышаем хп, некоторым по 25+ процентов. Почему крашер танк до сих пор с его абилками на урон вообще не понятно. На старте тгмс его роль была ломать кады, теперь ему проще ломать лица. Учитывая что идёт вместе с нерфом ап патрон (а там не ребаланс, а нерф давай честно говорить) теперь ап патроны рили ситуативны. Правда обычные патроны еще бесполезней стали от доп жира у ксено. 
Спитаку и сенту ап хп хорошо, выживать будут.
Зачем мили армор крашеру снижать?

2024-10-23 05:12 UTC, Tatarla commented
> Ребаланс хп и брони. Повышаем хп, некоторым по 25+ процентов. Почему крашер танк до сих пор с его абилками на урон вообще не понятно. На старте тгмс его роль была ломать кады, теперь ему проще ломать лица. Учитывая что идёт вместе с нерфом ап патрон (а там не ребаланс, а нерф давай честно говорить) теперь ап патроны рили ситуативны. Правда обычные патроны еще бесполезней стали от доп жира у ксено. 
> Спитаку и сенту ап хп хорошо, выживать будут.
> Зачем мили армор крашеру снижать?

Снижение мили армора - соответствующий баф милишников и вали
Каста, которая нужна чисто ради ломания кад - говно ебаное, что и доказывалось тремя годами игры. Непосредственно кроме разгона и стомпа по ЛЕЖАЧИМ урона у крашера около нихуя. Контрпик в виде дилея на выход из колючки будет добавлен со временем. ХП ему было апнуто непосредственно по причине того, что крашера убивало и ап, и хп. Сейчас он жрет хп пули(как и должен), а ап ему сносят 2/3 хп за ОДИН магазин. Это не играбельность ап? Как по мне - вполне себе очевидная играбельность.
Ребаланс ап патрон был произведен по проге Ксенона. Объективно, АП патроны были ЛУЧШЕ других патронов из-за того, что они банально имели дохуя урона при дохуя ап. Типо, они дамажили больше, чем ХП по практически всем кастам, кроме двух-трёх штук. Суть раздела ап и хп патронов была как раз в том, что если челам нужно выдать быстрый контрпик на ту или иную касту - свич боеприпасов и у малобронированной/бронированной касты отрывается еблище. А не бегать с 1 типом боеприпасов, который ебет всех из-за ошибок в расчете цифр урон/ап. К этому всё и идёт.
Обычные патроны - золотой стандарт, универсал. Не хочешь замарачиваться - носи их и будь вноси стабильный урон по любой цели. Да, это не будет ОГРОМНЫЙ урон.

2024-10-26 19:10 UTC, Helg2 requested changes
Здоровье крашеру снизь до 500

2024-11-06 08:44 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
> +	hard_armor = list(MELEE = 0, BULLET = 10, LASER = 0, ENERGY = 0, BOMB = 0, BIO = 0, FIRE = 0, ACID = 0)
Перемести это в стойку, а то кринж

2024-11-06 08:45 UTC, Helg2 requested changes
Перемести хард армор дефендера в стойку. А то получается у т1 ксеноса есть хард армор, а у т3 ксеносов почему-то нету.

2024-11-14 03:45 UTC, Tatarla commented
Харда ему нужна вне стойки
Пр прошел голосование

2024-11-14 05:56 UTC, merged