Rework some attachments, give mg60 aim mode and add all attach AR
PMC-Unga-Marines/Unga-Marines pull request #597
Opened 2024-10-25 16:13 UTC by Tatarla

## `Основные изменения`
На АРки теперь можно вешать любой обвес
МГ60 получила аим-мод
Всем прицелам(кроме ред-дота) добавлен аим-мод
Сошки ставятся 0.5 секунд
Бурст-фаер асемблер теперь не дает дебафов к точности (замена им слота подствола - уже огромная цена за использование)
Глушак снижает скорость пули на 30%, а не на 100%

## `Как это улучшит игру`
АРки и должны иметь возможность ставить на себя любые атачи
Малоиграбельные атачи бафаются > играбельны больше
МГ60 - пушка второй линии, которой требуется аим-мод для оптимальной игры

## `Ченджлог`
ТМ, будет изменено после фактического факта изменений

```
:cl:
add: Добавил новые механики или изменил геймплей.
add: Добавил больше вещей.
del: Удалил старые вещи.
qol: Сделал что-то более простым в использовании.
balance: Изменил баланс некоторых вещей.
fix: Исправил некоторые вещи.
sound: Добавил/Удалил/Изменил пару звуков.
image: Добавил/Удалил/Изменил некоторые спрайты.
map: Изменил составляющую карты.
spellcheck: Исправил несколько опечаток.
code: Изменил некую составляющую кода.
refactor: Переделал код в лучшую сторону.
config: Изменил настройки конфига.
admin: Что-то изменил в механиках для админов.
server: Что-то, в чем должны разбираться владельцы сервера.
/:cl:
```

2024-10-25 16:28 UTC, Helg2 commented on code/modules/projectiles/guns/rifles.dm
> +	actions_types = list(/datum/action/item_action/aim_mode)
Говна поел

2024-10-25 16:28 UTC, Tatarla commented on code/modules/projectiles/guns/rifles.dm
> +	actions_types = list(/datum/action/item_action/aim_mode)
Это лучше, чем давать на ред-дот аим мод

2024-10-25 18:04 UTC, homexp13 commented
(((МГ60 - пушка второй линии)))

2024-10-30 10:02 UTC, Helg2 requested changes
Нормально баффни м60, а не вот это вот всё

2024-11-06 08:49 UTC, Helg2 commented on code/modules/projectiles/guns/rifles.dm
> -		/obj/item/weapon/gun/flamer/mini_flamer/unremovable,
Этот атач есть у ЮПП-шной версии винтовки, зачем её убирать.

2024-11-06 08:56 UTC, Helg2 commented on code/modules/projectiles/guns/rifles.dm
> +		/obj/item/weapon/gun/energy/lasgun/lasrifle/pocket_beam,
Гениально, добавить подствольные аттачменты, чтобы они конфликтовали с _неснимаемым_ мини tx54

2024-11-06 08:57 UTC, Helg2 commented on code/modules/projectiles/guns/rifles.dm
> +	actions_types = list(/datum/action/item_action/aim_mode)
Всё еще кринж.

2024-11-06 08:58 UTC, Helg2 commented on code/modules/projectiles/attachables/underbarrel.dm
> -	burst_accuracy_mod = -0.1
Описание выше смени, если убираешь минусы у аттачмента.

2024-11-06 08:58 UTC, Helg2 commented on code/modules/projectiles/attachables/scope.dm
> +	add_aim_mode = TRUE
Кринж

2024-11-06 08:58 UTC, Helg2 commented on code/modules/projectiles/attachables/scope.dm
> +	add_aim_mode = TRUE
Кринж х2

2024-11-06 08:59 UTC, Helg2 commented on code/modules/projectiles/attachables/foldable.dm
> +	deploy_time = 0.5 SECONDS
Проблема сошек не в том что ты долго на них становишься, а в том что тебя из неё выталкивают марины, так как никакого визуального отображения сошек нету.

2024-11-06 09:00 UTC, Helg2 commented on code/modules/projectiles/attachables/muzzle.dm
> +	attach_shell_speed_mod = -0.3
До `-0.5` понизь, а то слишком жирно

2024-11-06 09:03 UTC, Helg2 requested changes
Баффать глушитель когда из него и так не видно кто, где и откуда в тебя стреляет можно конечно.

2024-11-07 14:10 UTC, Helg2 commented on code/modules/projectiles/attachables/foldable.dm
> +		user.move_resist = MOVE_FORCE_STRONG
Здесь `user_old_move_resist` записываешь

2024-11-07 14:10 UTC, Helg2 commented on code/modules/projectiles/attachables/foldable.dm
> +		user.move_resist = MOVE_RESIST_DEFAULT
А здесь `user_old_move_resist` присваиваешь к `move_resist`

2024-11-14 13:54 UTC, Helg2 reviewed
Встроенный аим у мг60 всё еще кринж.
Не уверен насчёт модификатора урона у б7, с учётом того что даже с -0.3 всё еще было сильно.

2024-11-15 06:14 UTC, Tatarla commented
Пока баланс сойдётся на 0.15
Аим у пулемета увы нужная ему вещь, это пулемет второй линии как-никак

2024-11-15 06:15 UTC, merged