Acid unwell
PMC-Unga-Marines/Unga-Marines pull request #609
Opened 2024-10-31 09:29 UTC by lorianss

## `Основные изменения`

Колодцы теперь нельзя ставить вплотную друг к другу, только через тайл.

## `Как это улучшит игру`

Когда Неоморф хватает нож, весь хайв бросает в дрожь.

## `Ченджлог`
:cl:
balance: Колодцы теперь нельзя ставить вплотную друг к другу, только через тайл.
/:cl:

2024-10-31 09:51 UTC, Tatarla commented
Теперь все будут знать, что ты виновен за это

2024-10-31 12:04 UTC, Istrelok2107 commented
Тимлид молодец

2024-11-01 06:51 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
> +	for(var/obj/structure/xeno/acidwell in range (1,T))
```suggestion
	for(var/obj/structure/xeno/acidwell in range (1, T))
```

2024-11-01 06:52 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
> +	for(var/obj/structure/xeno/acidwell in range (1,T))
```suggestion
	for(var/obj/structure/xeno/acidwell/well in range (1, T))
```
Дебил

2024-11-01 08:53 UTC, Helg2 requested changes
Выше.

2024-11-01 12:08 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
> +	for(var/obj/structure/xeno/acidwell/well in range (1, T))
```suggestion
	for(var/obj/structure/xeno/acidwell/well in range(1, T))
```

2024-11-01 12:17 UTC, merged