Новый смешной реагент за очки маринам
PMC-Unga-Marines/Unga-Marines pull request #610
Opened 2024-11-01 00:45 UTC by Istrelok2107

## `Основные изменения`
Добавлен нейростимулирующий реагент

введен реагент в маринвендоры за 25 очков и в карго за 200. увеличит мобильность маринов которые любят рисковать, но с последствиями при долгом нахождении реагента в организме и при встрече с Хемодайлом.
Реагент пуржит: ПП, ПП+, Наниты, Парацетамол(чтобы гении не комбинировали -0.1 скорости парацетамола с этим реагентом)
Имеет неприятную стадию привыкания. При взаимодействии с хемодайлом вводит в организм небольшое количество сопорофика и пуржится
при долгом нахождении в организме должно убивать сердце(наверное)
## `Как это улучшит игру`
Мары смогут носить Хеви???? Повышение актуальности дефайлера. Новые химсборки с реагентом.
## `Ченджлог`
```
:cl:
add: Введен нейростимулирующий реагент за очки маринов и в карго. HEAVY BUT FAAAAST!!!
/:cl:
```

2024-11-01 03:09 UTC, Tatarla commented
Цифры распиши, сколько юнитов в тик, сколько юнитов всего

2024-11-01 06:49 UTC, Helg2 commented on code/modules/reagents/reactions/other.dm
> +/datum/chemical_reaction/antipathy
```suggestion
/datum/chemical_reaction/sleeptoxin_two
```

2024-11-01 06:49 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +	taste_description = "tastes like sour coffee"
```suggestion
	taste_description = "sour coffee"
```

2024-11-01 06:49 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +	name = "MasSpeed"
```suggestion
	name = "MassSpeed"
```

2024-11-01 06:49 UTC, Helg2 commented on code/modules/reagents/reactions/other.dm
> +	name = "Antipathy"
```suggestion
	name = "Sleeptoxin"
```

2024-11-01 06:49 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +		if (89 to INFINITY)
```suggestion
		if(89 to INFINITY)
```

2024-11-01 06:49 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +/datum/reagent/medicine/masspeed/on_mob_life(mob/living/L, metabolism)
Без однобуквенных переменных пожалуйста.

2024-11-01 06:49 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +						E.take_damage(1.5*effect_str, TRUE)
```suggestion
					L.adjustOxyLoss(1.5 * effect_str)
					var/mob/living/carbon/human/H = L
					var/datum/internal_organ/heart/E = H.get_organ_slot(ORGAN_SLOT_HEART)
					if(E)
						E.take_damage(1.5 * effect_str, TRUE)
```

2024-11-01 06:49 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +			L.adjustStaminaLoss((4)*effect_str)
```suggestion
			L.adjustStaminaLoss((4) * effect_str)
```

2024-11-01 06:49 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +	trait_flags = TACHYCARDIC
Зачем добавлять этот трейт при добавлении в моба? Можно же нормально прописать

2024-11-01 07:17 UTC, Istrelok2107 commented
> Цифры распиши, сколько юнитов в тик, сколько юнитов всего

Цифры БаЛаНсНаЯ величина

2024-11-01 07:24 UTC, Istrelok2107 commented on code/modules/reagents/reagents/medical.dm
> +	trait_flags = TACHYCARDIC
Ну эээ, увеличивает пульс, на всяких сканерах

2024-11-01 08:49 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +	trait_flags = TACHYCARDIC
Зачем он в `on_mob_add`

2024-11-01 08:57 UTC, Helg2 commented
Распиши минимально в ченжлоге что делает реагент. Также `massspeed` бы заменить на что-то нормальное, хоть на тот же эфедрин.

2024-11-01 09:10 UTC, Istrelok2107 commented
> Распиши минимально в ченжлоге что делает реагент. Также `massspeed` бы заменить на что-то нормальное, хоть на тот же эфедрин.

Как по мне Эфедрин слишком банально, а моя шиза ничего смешнее чем отсылку на массмету не придумала

2024-11-01 10:38 UTC, Istrelok2107 commented
адекватнее ничего не придумал кроме замены Masspeed на MasTac

2024-11-01 11:39 UTC, Istrelok2107 commented
починил урон сердцу и чуть уменьшил его еблю

2024-11-01 12:38 UTC, kel593 commented
мастак (первитин)

2024-11-01 13:58 UTC, Istrelok2107 commented
меньше тряски

2024-11-01 14:12 UTC, Istrelok2107 commented
теперь нужно 18 юнитов Хемодайла которые попадут в кровь сразу чтобы пурджануть вещество

2024-11-01 18:50 UTC, Istrelok2107 commented
короче я понял примерно что в нем надо изменить чтобы был играбельным и используемым. как будет время займусь

2024-11-01 19:47 UTC, Istrelok2107 commented
Ап скорости

2024-11-01 20:30 UTC, Dark-Umbrella commented
А нахуй реагент, который подразумевается как халявный стимулон для тех кому лень его варить, с привыканием? Да ещё и с трёхминутным. 
+ о каких "новых хим сборках речь", если хуйня пуржит буквально единственные играбельные билды через пару-наниты. 
Высрал бы лучше, чтобы твоя хуйня реген нанитов останавливала или чё-то такое.
Сомнительная дичь. Тот же стимулон, пусть и даёт клон урон - не препятствует никаким другим сборкам реагентов, действует мгновенно и сразу по вкалыванию, а после окончания своего пребывания в организме даёт чёткий и ясный стан, а не мифический спорофик, который на маров нахуй не работает (любой атокс препятствует засыпанию мара).

Хуйня, баффай. 25 пойнтов сливать на 1-2 реагент-слеша дефайлера после неизбежного такла - такое себе.
Так же добавь реагенту иконку на худах, на манер Vali модуля, чтобы её видели как ксеносы, так и морпехи, и медики не переводили перидаксон на этих чуд в перьях.

2024-11-01 20:42 UTC, Istrelok2107 commented
> А нахуй реагент, который подразумевается как халявный стимулон для тех кому лень его варить, с привыканием? Да ещё и с трёхминутным.
> 
> * о каких "новых хим сборках речь", если хуйня пуржит буквально единственные играбельные билды через пару-наниты.
>   Высрал бы лучше, чтобы твоя хуйня реген нанитов останавливала или чё-то такое.
>   Сомнительная дичь. Тот же стимулон, пусть и даёт клон урон - не препятствует никаким другим сборкам реагентов, действует мгновенно и сразу по вкалыванию, а после окончания своего пребывания в организме даёт чёткий и ясный стан, а не мифический спорофик, который на маров нахуй не работает (любой атокс препятствует засыпанию мара).
> 
> Хуйня, баффай. 25 пойнтов сливать на 1-2 реагент-слеша дефайлера после неизбежного такла - такое себе. Так же добавь реагенту иконку на худах, на манер Vali модуля, чтобы её видели как ксеносы, так и морпехи, и медики не переводили перидаксон на этих чуд в перьях.

уже половину всех значений поменял сильно бафнув. Давай наспрайти эти иконки, так чтобы они еще как КР могли быть видны

2024-11-01 21:42 UTC, Helg2 commented
Там 8 пикселей спрайта, сам как-нибудь справишься

2024-11-01 22:26 UTC, Dark-Umbrella commented
[Pervityne.zip](https://github.com/user-attachments/files/17604599/Pervityne.zip)

:clueless:

2024-11-02 08:09 UTC, Istrelok2107 commented
Нихуя себе
Он реально наспрайтил

2024-11-02 12:32 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +			trait_flags = TACHYCARDIC
Долбоеб, впихни это в определение реагента. Нахуя оно тут.

2024-11-02 12:33 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +	custom_metabolism = REAGENTS_METABOLISM * 0
Гений блять

2024-11-02 12:34 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +			trait_flags = TACHYCARDIC
Однобуквенные переменные замени на нормальные слова.

2024-11-02 16:38 UTC, Istrelok2107 commented on code/modules/reagents/reagents/medical.dm
> +			trait_flags = TACHYCARDIC
Ночью займусь

2024-11-02 22:29 UTC, Istrelok2107 commented on code/modules/reagents/reagents/medical.dm
> +	custom_metabolism = REAGENTS_METABOLISM * 0
Оно не работало просто с нулем, хз в чем проблема была, вот как оно сейчас есть работает

2024-11-05 13:46 UTC, Istrelok2107 commented
Сделал так чтобы пуржилось только дефайлом либо реакцией с хемодайлом, убрал парацетамол из пуржа

2024-11-07 10:57 UTC, Helg2 reviewed
Я бы если честно попробовал вместо редкого но качественного урона, сделать частый но слабый урон.

2024-11-07 10:57 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +/datum/reagent/mastac/on_mob_life(mob/living/live, metabolism)
`our_living`

2024-11-07 10:57 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +/datum/reagent/mastac/on_mob_add(mob/living/live, metabolism)
`our_living`

2024-11-07 10:57 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +				var/mob/living/carbon/human/damage = live
`our_human`

2024-11-07 10:57 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +				var/datum/internal_organ/heart/heart_damage = damage.get_organ_slot(ORGAN_SLOT_HEART)
`our_heart`

2024-11-07 10:57 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +/datum/reagent/mastac/on_mob_delete(mob/living/delete, metabolism)
`our_living`

2024-11-07 10:57 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +					heart_damage.take_damage(15, TRUE)
```suggestion
				heart_damage?.take_damage(15, TRUE)
```

2024-11-07 10:57 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +			if(prob(0.1))
Здесь также можно сделать ранний ретурн

2024-11-07 10:57 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +	custom_metabolism = REAGENTS_METABOLISM * 0
```suggestion
	custom_metabolism = 0
```
Оно ничем не отличается, проблема не в этом

2024-11-08 12:15 UTC, Istrelok2107 commented
Ретурны ночью сделаю 
А так с телефона щас 1 цифру подправлю поскольку менял цену в карго

2024-11-09 21:05 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +			if(prob(0.1))
Забыл удалить

2024-11-09 21:55 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +			if(prob(0.1))
Ну и остальное как бы нужно подвинуть на тот же уровень что и `if` раннего ретурна.

2024-11-09 21:57 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +				our_heart?.take_damage(15, TRUE)
```suggestion
			if(prob(99.9))
				return
			to_chat(our_living, span_userdanger("OUUH MY HEART"))
			our_living.adjustOxyLoss(30)
			var/mob/living/carbon/human/damage = our_living
			var/datum/internal_organ/heart/our_heart = damage.get_organ_slot(ORGAN_SLOT_HEART)
			our_heart?.take_damage(15, TRUE)
```

2024-11-09 22:19 UTC, Helg2 requested changes
Проверь можно ли засунуть реагент в крио, для того чтобы раздюплить между множеством маринов. Если это так, то сделай в `on_mob_life` проверку ввиде на кол-во реагента меньшее 1 и ретурн. Если есть желание также можно сделать сообщение по-типу `to_chat(exposed_human, span_notice("<i>You feel nothing but a terrible aftertaste.</i>"))`

2024-11-11 20:52 UTC, Istrelok2107 commented
> Проверь можно ли засунуть реагент в крио, для того чтобы раздюплить между множеством маринов. Если это так, то сделай в `on_mob_life` проверку ввиде на кол-во реагента меньшее 1 и ретурн. Если есть желание также можно сделать сообщение по-типу `to_chat(exposed_human, span_notice("<i>You feel nothing but a terrible aftertaste.</i>"))`

Невозможно, в шприце всего 1 юнит, а крио сразу использует этот юнит. Максимум что можно сделать это раздублить внутри марина, а марину оно ничего не даст

2024-11-13 09:21 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +/datum/reagent/mastac/on_mob_delete(mob/living/delete, metabolism)
Актуально.

2024-11-13 09:22 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +			var/mob/living/carbon/human/damage = our_living
`our_human`

2024-11-13 09:24 UTC, Helg2 commented
Повысь шанс на урон до 1%, но урон снизь в 10 раз, так урон от мастака будет хоть иногда чувствоваться.

2024-11-13 09:56 UTC, Istrelok2107 commented
> > Невозможно, в шприце всего 1 юнит, а крио сразу использует этот юнит. Максимум что можно сделать это раздублить внутри марина, а марину оно ничего не даст
> 
> ![image](https://private-user-images.githubusercontent.com/93882977/385687098-b5b2beed-7aab-4706-a75c-35e84ff97a71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTIwMjksIm5iZiI6MTczMTQ5MTcyOSwicGF0aCI6Ii85Mzg4Mjk3Ny8zODU2ODcwOTgtYjViMmJlZWQtN2FhYi00NzA2LWE3NWMtMzVlODRmZjk3YTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA5NTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYjNkNWVlYWZiZTA2MjQxOWJmMzBjY2EzY2RjM2Q3NjNmNTAxZWExOTE5MGQzZTgzY2IzMjk5ODdjZDM4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.31Geh9kjKpkhLaHQXYyv6j1Ee4gnGlKChSh-mkXwJZs) С нанитами так можно, значит и с твоей фигней.

У меня на локалке сразу юнит сжирало, без разделения

2024-11-13 09:58 UTC, Istrelok2107 commented
> Повысь шанс на урон до 1%, но урон снизь в 10 раз, так урон от мастака будет хоть иногда чувствоваться.

Спам в чат, да и комфортнее играть когда очень редко, но сильнее. Дело комфорта

2024-11-13 10:00 UTC, Istrelok2107 commented
Ладно, сделаю проверку чтобы крио не дублировало

2024-11-13 10:07 UTC, Helg2 commented
> Спам в чат, да и комфортнее играть когда очень редко, но сильнее. Дело комфорта

1 раз в 3 минуты не особо спамит, а 1 раз в 30 минут звучит как абсолютная халява, дело не в комфорте, а в балансе.

2024-11-13 10:10 UTC, Istrelok2107 commented
> > Спам в чат, да и комфортнее играть когда очень редко, но сильнее. Дело комфорта
> 
> 1 раз в 3 минуты не особо спамит, а 1 раз в 30 минут звучит как абсолютная халява, дело не в комфорте, а в балансе.

Чистая удача, мне за первые 15 минут на шипе снесло 30хп/2 раза

2024-11-13 10:11 UTC, Istrelok2107 commented
Плюс 15 урона сердцу уже режут почти половину стамины, плюс вроде дает пеин

2024-11-13 10:15 UTC, Istrelok2107 commented
30 урона должны практически всю стамину сжирать, с помощью пери не вылечить
Либо эвакаться на шип и лечится автодоком/шипмедом
Либо делать на земле операцию и получать инфекцию с которой воевать опасно, а длиться она может 1-10 минут

2024-11-13 10:16 UTC, Istrelok2107 commented
У примеру, открылась рана на груди - огромный шанс получить негроз груди(сдохшие органы)

2024-11-13 10:18 UTC, Istrelok2107 commented
Достаточно 1 дефайла чтобы полностью пуржануть - скилл ишуй ксен если они не могут прожать кастсвап и дефайлнуть чела с иконкой

2024-11-13 10:24 UTC, Helg2 commented
> Плюс 15 урона сердцу уже режут почти половину стамины, плюс вроде дает пеин

Я и говорю, уменьши урон в 10 раз, но сделай чаще в 10 раз. 1.5 за 3 минуты.

2024-11-13 11:08 UTC, Istrelok2107 commented
> > Плюс 15 урона сердцу уже режут почти половину стамины, плюс вроде дает пеин
> 
> Я и говорю, уменьши урон в 10 раз, но сделай чаще в 10 раз. 1.5 за 3 минуты.

При повреждении сердце кукла начинает grab his chests
Не будет прикольно если если 10% маров на корабле будут бегать с этими автоэмоутами

2024-11-13 11:09 UTC, Istrelok2107 commented
Редкий, сильный урон нужен для соблюдения красоты да и если в бою прокнет, то минус -30 окси очень даже могут иногда убить марина
Можно добавить обычного урона, к примере 20-30 брута при проке

2024-11-13 11:10 UTC, Istrelok2107 commented
Сумарно за прок редкий будет нанесено 60 урона мгновенно. Что пиздец как неприятно и может убить даже в легком крите

2024-11-13 12:48 UTC, Helg2 commented
> При повреждении сердце кукла начинает grab his chests Не будет прикольно если если 10% маров на корабле будут бегать с этими автоэмоутами

Не прикольно - это 0.4 скорости ценою аж в 15 урона сердцу раз в 30 минут.

2024-11-14 03:41 UTC, Tatarla commented
Согласен, урон сердцу нужен, иначе это самые халявные 0.4 спида в этой жизни

2024-11-14 08:21 UTC, Istrelok2107 commented
> Согласен, урон сердцу нужен, иначе это самые халявные 0.4 спида в этой жизни

Урон сердце примерно такой же как и был.
Просто тебя теперь не может оно убить в черезвычайной ситуации. Хельг молодец.
Раньше в случае чего окси урон мог сильно надамажить стамину и в крите добить. После нерфа по предложению хельга он не сможет добить в крите

2024-11-19 23:05 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +/datum/reagent/mastac/on_mob_delete(mob/living/delete, metabolism)
Все еще актуально.

2024-11-19 23:06 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +			to_chat(our_human, span_warning("It seems that your body has become accustomed to new conditions. But the heart is working hard"))
```suggestion
			to_chat(our_human, span_notice("Your heart is jumping out of your chest."))
		if(41)
			to_chat(our_human, span_warning("It seems that your body has become accustomed to new conditions. But the heart is working hard."))
```

2024-11-19 23:06 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +	to_chat(our_human, span_userdanger("You feel like your heart will stop at any second."))
```suggestion
	to_chat(our_human, span_userdanger("You feel like your heart could stop at any moment."))
```

2024-11-26 20:53 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +		our_living.reagents.add_reagent(/datum/reagent/toxin/xeno_hemodile, 10)
```suggestion
```
При пурже реагента получаешь 10 юнитов гемодила в подарок

2024-11-27 01:55 UTC, Istrelok2107 commented on code/modules/reagents/reagents/medical.dm
> +		our_living.reagents.add_reagent(/datum/reagent/toxin/xeno_hemodile, 10)
Это антидюп прикол, чтобы оно допуржило реагент в крови+дало спорофика
Для пуржа нелетально, для дюперов не прикольно, в бою так сможет сделать только дефуфел

2024-11-27 06:38 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +		our_living.reagents.add_reagent(/datum/reagent/toxin/xeno_hemodile, 10)
Прикол хуёвый.

2024-11-27 16:26 UTC, Istrelok2107 commented on code/modules/reagents/reagents/medical.dm
> +		our_living.reagents.add_reagent(/datum/reagent/toxin/xeno_hemodile, 10)
Зато рабочий. Да и при каких нибудь рантаймах все равно пуржанет при дюпе. Так что это надо оставить

2024-11-28 23:20 UTC, Istrelok2107 commented
0.12 потому что мыкола хуево посчитал свои 0.225

2024-11-29 07:50 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +		our_living.reagents.add_reagent(/datum/reagent/toxin/xeno_hemodile, 10)
Нормально просто пурдж сделай.

2024-11-30 11:11 UTC, Istrelok2107 commented on code/modules/reagents/reagents/medical.dm
> +		our_living.reagents.add_reagent(/datum/reagent/toxin/xeno_hemodile, 10)
Тут дело в том что он в крови сам регенерирует, и он просто может нормально не запуржиться - проверено в локалке

2024-11-30 12:37 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +		our_living.reagents.add_reagent(/datum/reagent/toxin/xeno_hemodile, 10)
Он чисто логически не может регенерировать, так тут стоит ретурн, он части с самодобавлением реагента попросту не достигает

2024-12-03 08:44 UTC, Istrelok2107 commented
насрано

2024-12-13 07:36 UTC, Helg2 commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +	description_overlay = "Mt"
```suggestion
	description_overlay = "Nf"
```

2024-12-13 07:37 UTC, Helg2 approved these changes
Сойдет

2024-12-13 09:35 UTC, merged