Door kill
PMC-Unga-Marines/Unga-Marines pull request #614
Opened 2024-11-02 15:25 UTC by lorianss

## `Основные изменения`

Между дверьми теперь должно быть минимум 2 тайла для их постройки

## `Как это улучшит игру`

Не будет раковых застроек всего дверьми, отвратительных по многим причинам.

## `Ченджлог`

```
:cl:

balance: Теперь между дверьми должно быть минимум 2 тайла для их постройки.

/:cl:
```

2024-11-02 15:27 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/abilities.dm
> +
Сделай тогда уже цикл `switch()` наверное

2024-11-02 15:29 UTC, Helg2 requested changes
2 слишком много

2024-11-05 08:43 UTC, Istrelok2107 commented
Как по мне убивать двери - хуйня

2024-11-06 10:42 UTC, Helg2 commented
Не является решением проблемы. Не будут срать дверьми, насрут резины/китайскую стену.

2024-11-12 11:58 UTC, Istrelok2107 commented
Ненадо это переоткрывать, убейте и забудьте

2024-11-13 12:36 UTC, Tatarla commented
ПР прошел депутатов, будет замерджен в любом случае

2024-11-13 12:46 UTC, Helg2 commented
Хуйня твои депутаты, у них уже срок прошёл.

2024-11-14 03:43 UTC, Tatarla commented
Проголосовали они ещё в свой срок

2024-11-14 08:47 UTC, Helg2 commented
И пр все еще хуйня.

2024-11-14 10:07 UTC, Istrelok2107 commented
заебали

2024-11-14 10:16 UTC, Helg2 commented
Все еще не решение проблемы. Но лишит возможности делать застройку с дверями.

2024-11-14 10:31 UTC, lorianss commented
КАКОЙ ПРОБЛЕМЫ ХУЕСОСЫ. ЕДИНСТВЕННАЯ ЦЕЛЬ ЭТОГО ПРА - ИЗБЕЖАТЬ ЗАСЁРА ВСЕГО ДВЕРЬМИ, КОТОРЫЕ В БОЛЬШЕМ КОЛИЧЕСТВЕ СМЕРТЕЛЬНО МЕШАЮТ КСЕНОСАМ И ПРИ ЭТОМ НЕ ВЫЗЫВАЕТ ХОТЬ КАКИХ ЛИБО ДОСТОЙНЫХ ПРОБЛЕМ У МАРОВ.
ЕСЛИ БУДУТ ВСЁ ЗАСЕРАТЬ СЛИЗЬЮ - ЭТО ХОРОШО, ОНА НЕ МЕШАЕТ, ТОЛЬКО ПОМОГАЕТ. СТЕНАМИ? ЕЩЁ ЛУЧШЕ.

ЭТОТ ПОСЫЛ ПОНЯЛ КАЖДЫЙ ДЕПУТАТ, ДАЖЕ НЕ ИГРАЮЩИИ НА КСЕНОСАХ, ВИДИМО ИГРОВОГО ОПЫТА ХВАТАЕТ

КАКУЮ ПРОБЛЕМУ ВИДИТЕ ВЫ?

Ивил, подписаться.

2024-11-14 10:40 UTC, sluttykitty commented
> Все еще не решение проблемы. Но лишит возможности делать застройку с дверями.

как же запретит делать застройку с дверьми дааа. 
для тупых: обычно застройка это кубики 2 на 2. Смекаешь? именно столько, сколько надо клеток между дверьми в этом пре

2024-11-15 06:04 UTC, merged