Tank high pop lock
PMC-Unga-Marines/Unga-Marines pull request #615
Opened 2024-11-02 21:21 UTC by definitelynotspaghetti

## `Основные изменения`

Для танкиста теперь нужно столько же маров, сколько и на пилота меха. Для АПЦ ничего не изменилось

## `Как это улучшит игру`

Слишком сильная хуйня против ксен для среднего онлайна на сервере в 50-60 человек, к тому же при хайпопе админы и так почти всегда будут открывать слоты на него.

## `Ченджлог`

Для танкиста нужно 80 поинтов, как и для пилота меха

```
:cl:
balance: Увеличил требования в количестве маров для роли танкиста в два раза.
/:cl:
```

2024-11-03 09:16 UTC, Tatarla commented
Снижай, у мехпилота настолько ебанутый лок, что он не открывался у нас даже при 140 игроках

2024-11-03 10:40 UTC, Tatarla commented
Проверь еще, что там оба слота танкиста открывается, иначе будет смешная хуйня, что танк без водилы/заряжающего

2024-11-04 06:58 UTC, Helg2 commented on code/datums/jobs/job/shipside.dm
> +		add_job_positions(2) //always 2 there are, a master and an apprentice
Что это делает вообще?

2024-11-04 06:59 UTC, Helg2 requested changes
Чтобы это полноценно работало, нужно в списки `jobworth` которые толком не прописаны у половины работ, в кои-то веки доделать.

2024-11-04 07:59 UTC, closed without merging