Удаление кишки лавового озера на Магмуре
PMC-Unga-Marines/Unga-Marines pull request #625
Opened 2024-11-04 17:38 UTC by Tatarla

## `Основные изменения`
Обрезание кишки и лавового озера на Магмуре

## `Как это улучшит игру`
Меньше поводов для педале-додовских отношений

## `Ченджлог`
```
:cl:
map: На Магмуре была удалена кишка на лавовом озере
/:cl:
```

2024-11-04 18:07 UTC, lorianss commented
На самом деле можно же просто кишку заново вырезать в скале резаком, или я что то не понимаю?
Если так, то бессмысленный пр

2024-11-04 18:16 UTC, Tatarla commented
Заебутся резать

2024-11-04 21:52 UTC, Helg2 commented
Маленький коридорчик справа можно и оставить

2024-11-05 06:47 UTC, Istrelok2107 commented
Халяль, но один хуй будут прямо с лз туда копать

2024-11-05 12:57 UTC, Helg2 requested changes
Маленький коридорчик справа от озера закрыл, но ручей не убрал.

2024-11-06 14:24 UTC, kel593 commented
Это такой конец, они занёрфили Додо

2024-11-07 12:47 UTC, Helg2 approved these changes

2024-11-07 12:47 UTC, merged