Add carrier changes
PMC-Unga-Marines/Unga-Marines pull request #633
Opened 2024-11-08 18:24 UTC by mister-onion

## `Основные изменения`

_Добавление новой способности_

**Создание неста из резины**

Стоимость плазмы = 200
КД = 20s

_характеристики_
**Поднятие ХП, плазмы, армора, сила атаки**
Melee damage = 20>22
Plasma_max = 800>1000
plasma_gain = 38>45
max_health = 325>425
soft_armor = list (MELEE = 15>30, BULLET = 15>30, LASER = 15>30, ENERGY = 15>30, BOMB = 0, BIO = 5, FIRE = 0>25, ACID = 5)

(Так же поднято количество хаггеров для хранения 7>9)
 
_способности_
**Call younger** - 20s > 10s КД 
**Throw hugger** - 3s > 2s КД
**Spawn hugger** - 10s > 5s КД
 
## `Как это улучшит игру`

Помимо геймплея аля расставляешь ловушки и ждешь, будет больше шансов выжить на фронте и быть полезным. Новая способность добавит касте больше функционала и самостоятельности, теперь не придется отвлекать других ксенов и ждать их, что так же повышает шанс на захват в нест.

## `Ченджлог`

```
:cl:
add: Добавлена способность для постройки неста керриеру. Стоимость плазмы 200, КД 20с.
balance: способности: Call younger - 20s > 10s КД;  Throw hugger - 3s > 2s; КД Spawn hugger - 10s > 5s КД. Характеристики:Melee damage = 20>22;Plasma_max = 800>1000;plasma_gain = 38>45;max_health = 325>425
soft_armor = list (MELEE = 15>30, BULLET = 15>30, LASER = 15>30, ENERGY = 15>30, BOMB = 0, BIO = 5, FIRE = 0>25, ACID = 5).
/:cl:
```

2024-11-08 20:01 UTC, Helg2 commented
Нормально изменения распиши.

2024-11-08 21:18 UTC, Helg2 commented
Желательно подробно расписать, также уточни что абилку ты добавил не просто в игру а именно керриеру. Это всё таки будет отображаться в игре при заходе, и цель ченжлога в том чтобы игроки могли полноценно следить за изменениями.

2024-11-08 22:21 UTC, Helg2 commented
С точными цифрами желательно.

2024-11-09 06:47 UTC, Istrelok2107 commented
Хельг не еби сильно новичка в коде

2024-11-09 15:17 UTC, Ghostkokos commented
Крута хочу чтобы был мерж 👍

2024-11-09 19:45 UTC, Istrelok2107 commented
на фоне возвращения спрей насадки можно и бафнуть керю

2024-11-10 12:04 UTC, Istrelok2107 commented
Сомнительно что керя постоянно может теперь генерировать хаггеров. Яйца ему теперь бесполезны. ХП хз нахуя ему бафать. Поскольку его задача не вблизи пиздить

2024-11-10 13:27 UTC, Istrelok2107 commented
> > Сомнительно что керя постоянно может теперь генерировать хаггеров. Яйца ему теперь бесполезны. ХП хз нахуя ему бафать. Поскольку его задача не вблизи пиздить
> 
> до этого писал что раз насадки вернули можно и керю баффнуть. А сейчас удалил уже, ладно? Потом объясню если так сильно этот вопрос волнует

да, вопросы? Я могу бухим все что угодно писать, так и в здравом уме тоже. Иногда во мне говорит Тайлер Дерден, иногда второй Тайлер Дерден

2024-11-15 13:35 UTC, Tatarla requested changes
Мили урон вернуть на 20
Армор вернуть на старое значение
Плазмареген вернуть на старое
Максимум плазмы до 900
Призыв назад на 20 секунд

2024-11-16 07:25 UTC, Istrelok2107 commented
> > Мили урон вернуть на 20 Армор вернуть на старое значение Плазмареген вернуть на старое Максимум плазмы до 900 Призыв назад на 20 секунд
> 
> мили урон окей, призыв окей, плазма ладно, плазмареген тоже похуй, мб броню оставить?

Радуйся что не закрыли

2024-11-22 06:41 UTC, Tatarla commented
Хотя и считаю, что насрали в статах, но блядей будет корежить

2024-11-22 06:42 UTC, merged