Steel crest
PMC-Unga-Marines/Unga-Marines pull request #654
Opened 2024-11-13 20:39 UTC by homexp13

## `Основные изменения`

https://github.com/user-attachments/assets/4bc3c32e-5840-4e1c-830c-7b867c3742c9

стрейн для дефендера

## `Как это улучшит игру`

![image](https://github.com/user-attachments/assets/2692cb1c-1fab-4290-8ce5-4a094d5f1718)

## `Ченджлог`

```
:cl:
add: Steel crest
/:cl:
```

2024-11-13 22:39 UTC, Helg2 commented on code/datums/keybinding/xeno.dm
> +
Выставь значения по дефолту.

2024-11-13 22:41 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
> +	var/max_dist = 2 - (X.crest_defense)
Зачем использовать в формуле булеан?

2024-11-14 03:36 UTC, Tatarla commented
Распиши пр по людски

2024-11-14 09:34 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
> +		addtimer(CALLBACK(src, PROC_REF(enraged), owner), 1) //CM use timer, so i do
```suggestion
		addtimer(CALLBACK(src, PROC_REF(enraged), owner), 0.1 SECONDS) //CM use timer, so i do
```

2024-11-14 09:34 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
> +
```suggestion
```

2024-11-14 09:34 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
> +
```suggestion
```

2024-11-14 09:34 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
> +
```suggestion
```

2024-11-14 11:49 UTC, HeXo4yXeH commented
Жесть КД на голову 10 секунд, но я зайду потесчу это завтра, надеюсь это будет круто.

2024-11-14 12:43 UTC, homexp13 commented on code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
> +		T = temp
Это микро оптимизация, где то уже писал об этом. Если в теле цикла temp писать, то переменная будет каждый раз при итерации цикла участок памяти заполнять/очищать, а так просто переписывать значение.
У шрики флинг аналогичным способом прописан

2024-11-14 19:02 UTC, homexp13 commented on code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
> +			FT.set_fortify(FALSE)
не знаю как нормально сделать

2024-11-14 19:18 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
> +			FT.set_fortify(FALSE)
```suggestion
		//Fortify prevents dragging due to the anchor component. // TODO: Unshitcode me
		if(actions_by_path[/datum/action/ability/xeno_action/fortify])
			var/datum/action/ability/xeno_action/fortify/FT = actions_by_path[/datum/action/ability/xeno_action/fortify]
			FT.set_fortify(FALSE)
		else if(actions_by_path[/datum/action/ability/xeno_action/fortify/steel_crest])
			var/datum/action/ability/xeno_action/fortify/FT = actions_by_path[/datum/action/ability/xeno_action/fortify/steel_crest]
			FT.set_fortify(FALSE)
```

2024-11-14 19:27 UTC, Helg2 requested changes
По коду вроде норм

2024-11-14 19:46 UTC, Helg2 approved these changes
По коду вроде норм

2024-11-15 06:16 UTC, Tatarla commented
Спрайт уникальный прикрутить ему нужно
И гибанимку тоже

2024-11-15 12:43 UTC, homexp13 commented
> Спрайт уникальный прикрутить ему нужно И гибанимку тоже

![image](https://github.com/user-attachments/assets/bf73b8f5-dcbf-45a1-a315-6ca5b5add3e0)

2024-11-28 15:08 UTC, merged