Carrier buff
PMC-Unga-Marines/Unga-Marines pull request #658
Opened 2024-11-14 13:02 UTC by MeowEmiya

## `Основные изменения`

## `Как это улучшит игру`

## `Ченджлог`

```
:cl:
add: Добавил новые механики или изменил геймплей.
add: Добавил больше вещей.
del: Удалил старые вещи.
qol: Сделал что-то более простым в использовании.
balance: Изменил баланс некоторых вещей.
fix: Исправил некоторые вещи.
sound: Добавил/Удалил/Изменил пару звуков.
image: Добавил/Удалил/Изменил некоторые спрайты.
map: Изменил составляющую карты.
spellcheck: Исправил несколько опечаток.
code: Изменил некую составляющую кода.
refactor: Переделал код в лучшую сторону.
config: Изменил настройки конфига.
admin: Что-то изменил в механиках для админов.
server: Что-то, в чем должны разбираться владельцы сервера.
/:cl:
```

2024-11-14 13:07 UTC, Ghostkokos commented
этому пиару нужен спидмердж

2024-11-14 13:08 UTC, Istrelok2107 commented
Уже вижу 70% хайва из керь
Спидмерж

2024-11-14 18:53 UTC, Helg2 commented
Я решил что ты идёшь нахуй.

2024-11-14 20:22 UTC, Tatarla commented
Сыграем в тмах, голосование депутатов прошло

2024-11-15 13:39 UTC, Tatarla requested changes
Скорость роста старую

2024-11-22 06:40 UTC, merged