Port modules from offb|
PMC-Unga-Marines/Unga-Marines pull request #666
Opened 2024-11-17 19:10 UTC by Etrnlmelancholy

## `Основные изменения`

Заменяет спрайты модулей на те что стоят сейчас на оффах.

## `Как это улучшит игру`

Они в разы красивее. Они приятнее глазу. Тюр не превращает тебя в какую то кучу пикселей ебаных. А еще они РАСПОЛОЖЕНЫ КРАСИВО ВНУТРИ ДМИ ФАЙЛА
![image](https://github.com/user-attachments/assets/730ba78b-ec49-40b4-b4a7-11d8e665684e)

## `Ченджлог`

```
:cl:Etrnlmelancholy
image: Замена всех спрайтов модулей на оффовские.
/:cl:
```

2024-11-17 19:16 UTC, Helg2 commented
Писать свой ник в `:cl:` не обязательно так как, твой ник совпадает с тем что ты туда пишешь.

2024-11-17 19:16 UTC, Tatarla commented
Приложи скрин, как выглядит в игре
Можно обойтись основными бесплатными модулями

2024-11-17 19:17 UTC, Tatarla commented
Желательно в составе имеющихся дрипов

2024-11-17 19:18 UTC, Helg2 requested changes
Картинки с демонстрацией в игре с 4-ёх сторон.

2024-11-17 19:21 UTC, Etrnlmelancholy commented
![image](https://github.com/user-attachments/assets/c894d104-fe0c-4d19-a7ae-96b6e4629dc1)
сука какова хуя у меня на локалке меню не работает

2024-11-17 19:39 UTC, Dark-Umbrella commented
Хуйню какую-то высрал. Текущие модули более чем приятны, и их, бляди вы такие, _видно_. Гонясь за картинкой не забывайте, что играете в игру, где есть игровые условности, и помимо вас, примерно понимать что за говно на вас напялено должен и противник. А не то, как вы хотите, завесится плащами заправленными в трусы, и спрайты модулей превратив в 3 пикселя на кукле.

2024-11-17 19:43 UTC, Etrnlmelancholy commented
До модулей: 
![image](https://github.com/user-attachments/assets/f8d9044b-8677-4aa4-818b-788567b6ef78)

После модулей:
![image](https://github.com/user-attachments/assets/d323db5b-206b-41b7-9346-44ed08c7c50d)

Выглядит "более чем приятно" in question

2024-11-18 09:20 UTC, CheBokJam commented
Может добавим эти модули по типу нового ксенонавта и старого, нового джаггера и старого?

2024-11-18 11:37 UTC, homexp13 commented
![image](https://github.com/user-attachments/assets/99861b54-1951-4dbe-a116-3d4d1963f369)
одобряю

2024-11-18 11:39 UTC, Tatarla commented
Насрал, исправляй удаленные модули

2024-11-18 13:35 UTC, Etrnlmelancholy commented
Бля домой приду докину

2024-11-19 16:31 UTC, Etrnlmelancholy commented
@Tatarla

2024-11-21 19:29 UTC, Helg2 requested changes
Модули сомов у нас были отдельно сделаны оранжевыми вместо жёлтого.
Также некоторые ксенонаутские версии модулей, которые слишком устарели, я удалял.

Хуйня переделывай. Просто заменить файлы не вариант.

2024-11-21 21:38 UTC, Etrnlmelancholy commented
Че значит устарели, ты еблан чтоли, пр называется порт с оффов

2024-11-28 09:34 UTC, Helg2 commented
Нет так нет.

2024-11-28 09:34 UTC, closed without merging