Furry update
PMC-Unga-Marines/Unga-Marines pull request #668
Opened 2024-11-18 13:54 UTC by homexp13

## `Основные изменения`

новая расса свинолюдей

## `Как это улучшит игру`

![image](https://github.com/user-attachments/assets/2545b609-c0f2-462f-a1a2-71219e11407e)

## `Ченджлог`
```
:cl:
add: Добавлена расса свинойлюдей
/:cl:
```

2024-11-18 13:57 UTC, SanecMan commented
Свинья это тема

2024-11-18 14:00 UTC, SanecMan commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +	else if(S.name == "Vatborn" || S.name == "Pigman" || S.name == "Early Vat-Grown Human" || S.name == "Vat-Grown Human")
ахуй свиньи ватборны

2024-11-18 14:02 UTC, SanecMan commented on code/modules/mob/living/carbon/human/species.dm
> +	namepool = /datum/namepool/vatborn
![image](https://github.com/user-attachments/assets/535a1112-2d5f-4829-8806-21618f4f8376)
А зачем свиньям пул имён ватборнов? Они тип искусственно выращены?

2024-11-18 14:04 UTC, SanecMan commented on code/modules/mob/new_player/sprite_accessories.dm
> +
а зачем

2024-11-18 14:05 UTC, homexp13 commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +	else if(S.name == "Vatborn" || S.name == "Pigman" || S.name == "Early Vat-Grown Human" || S.name == "Vat-Grown Human")
это номенклатура по госту

2024-11-18 15:25 UTC, Helg2 requested changes
Цветовая гамма головы не совпадает с телом.

2024-11-18 18:26 UTC, homexp13 commented
![image](https://github.com/user-attachments/assets/a1df4d92-d668-4c23-a2e2-94131dde5e13)
![image](https://github.com/user-attachments/assets/2ab92808-7739-4a71-9ee3-c93a227a9cda)
![image](https://github.com/user-attachments/assets/b50aa1cc-4d2a-4ac8-947d-31df1fe9cdd0)
![image](https://github.com/user-attachments/assets/9c383da1-5a45-4b89-ae85-4dddd8639d8b)
поменял

2024-11-19 10:10 UTC, GOLAj100 commented
ООО обед, сам идёт к нам)

2024-11-19 11:31 UTC, Istrelok2107 commented
Надо чтобы когда вырезаешь сердце, вместо сердца падали свинные рёбрышки

2024-11-19 20:43 UTC, LoneAsket commented
Не трогайте, это на новый год)

2024-11-28 15:09 UTC, Tatarla commented
Переделай это в фичу для бустеров 3 тира

2024-12-04 15:35 UTC, closed without merging