Mimir great again V2
PMC-Unga-Marines/Unga-Marines pull request #670
Opened 2024-11-19 15:03 UTC by CheBokJam

## `Основные изменения`
Увеличил защиту от кислоты у обеих версий мимимирки, у МК1 урезал защиту от газов, уменьшил урон от попадания в колодцы при частичном/полном комплекте мимира и шлема, поднял цену МК2 в карго до 160 поинтов.

## `Как это улучшит игру`
Морпехи в МК2 и МК1 будут отлетать от плевков дольше (в МК2 в почти два раза больше плевков для крита). Теперь урон (вернее АП) колодцев дополнительно режется в зависимости от надетого шлема + версии мимира. МК2 позволяет ходить в кислотных облаках и прочих дымах без стыда и совести (возможно надо нерфить), МК1 же справляется в два раза хуже и будет пропускать урон от кислотных облаков и пропускать в тело газы (до этого у МК1 был такой же полный игнор всех газов как у МК2).
Цена была поднята исходя из простой логики: тюр даёт небольшое повышение выживаемости (+5/+10) против самого частого урона, мимир же почти закрывает вопрос с рендж кастами, газами и так ненавистными колодцами.

Меньше бесполезных модулей в карго.

## `Ченджлог`

```
:cl:
balance: Защита мимира 1 от кислоты 5 -> 10, защита от газов снижена в два раза.
balance: Защита мимира 2 от кислоты 10 -> 25.
balance: Снижение урона от колодцев в зависимости от надетого шлема с мимиром + версии мимира.
/:cl:
```

2024-11-19 20:07 UTC, Istrelok2107 commented
balance: Защита мимира 1 от кислоты 5 -> 10, защита от газов снижена в два раза - ГОВНО

2024-11-19 20:07 UTC, Istrelok2107 commented
весь пр - нерф мимира

2024-11-20 11:08 UTC, CheBokJam commented
> весь пр - нерф мимира

Буст защиты мимиров в два/два с половиной раза; доп снижение урона от колодцев для надетого модуля - это всё точно нерф. МК1, игнорящий полностью газы и делающий МК2 более бессмысленным на его фоне - точно не хуёвое игровое решение. Верю, охотно верю.

2024-11-20 19:55 UTC, Istrelok2107 commented
> > весь пр - нерф мимира
> 
> Буст защиты мимиров в два/два с половиной раза; доп снижение урона от колодцев для надетого модуля - это всё точно нерф. МК1, игнорящий полностью газы и делающий МК2 более бессмысленным на его фоне - точно не хуёвое игровое решение. Верю, охотно верю.

Твои идеи - полная хуйня

2024-11-22 10:28 UTC, Tatarla requested changes
Старый ценник поставь

2024-11-22 12:26 UTC, CheBokJam commented
> Старый ценник поставь

Исполнено, мой повелитель

2024-11-28 11:12 UTC, Helg2 commented on code/modules/xenomorph/acidwell.dm
> +		stepper.apply_damage(charges * 10, BURN, BODY_ZONE_PRECISE_R_FOOT, ACID,  penetration = 33 - 20 * H.get_permeability_protection()) //without providing full protection against them
Сделай отдельно проверку на то является ли наступивший моб человеком, ибо если какой-нибудь симпл моб, по-типу коровы, наступит на колодец, то из-за того что она не является хуманов, то мы получим рантайм.

2024-11-28 12:36 UTC, CheBokJam commented on code/modules/xenomorph/acidwell.dm
> +		stepper.apply_damage(charges * 10, BURN, BODY_ZONE_PRECISE_R_FOOT, ACID,  penetration = 33 - 20 * H.get_permeability_protection()) //without providing full protection against them
Рантаймов тоже нет как следствие

2024-11-28 12:40 UTC, Helg2 commented on code/modules/xenomorph/acidwell.dm
> +		stepper.apply_damage(charges * 10, BURN, BODY_ZONE_PRECISE_R_FOOT, ACID,  penetration = 33 - 20 * H.get_permeability_protection()) //without providing full protection against them
Хм, ладно

2024-11-29 10:07 UTC, Tatarla approved these changes

2024-11-29 10:07 UTC, merged