SG-85 goes BRRR
PMC-Unga-Marines/Unga-Marines pull request #671
Opened 2024-11-19 15:06 UTC by CheBokJam

## `Основные изменения`
Вернул статы СГ-85 до его баффа (нерфа) Татаром, добавил шаттер на 3 секунды.

## `Как это улучшит игру`
Вилка для стен станет миниганом, способным любой касте нанести урон, как и полагается СГ, и снизить защиту для челиков с ХП патронами (такие существуют?). Брать слот СГшера ради сноса стен и убийства 6 ксеносов из каст Т1-Т2, когда абсолютно любой негр ходит под ферами защиты кинга/квины + апгрейдами и минусовым 20 АП у пушки - вышка парада кринжа. Для этих целей есть ХП патроны у бесплатных пукалок.
Да - с этой пушкой ты не пойдёшь беззаботно рашить застрой в сравнении с Т25 (абалдеть, а чё другой геймплей существует?), но, стреляя из-за спин союзников, заливая всё пространство пулями и прикрывая тыл, можно принести не меньший импакт, тем более со снижением брони на 20% на 3 секунды с выстрела.

## `Ченджлог`

```
:cl:
balance: Добавил шаттер (минус 20% брони) на 3 секунды.
balance: Урон 25 -> 10, АП -15 -> 25.
/:cl:
```

2024-11-19 16:08 UTC, Tatarla requested changes
Жестко насрал
Количество боеприпасов в паверпаке до 1000
Изменение урона и пенетры сомнительно, крайне сомнительно, ты сюда добавляешь еще и шаттер сверху, что делает пушку с хорошим АП еще более ебущей из-за эффекта шаттера, который она поддерживает 24/7 из-за своей скорострельности

2024-11-19 16:26 UTC, CheBokJam commented
> Жестко насрал Количество боеприпасов в паверпаке до 1000 Изменение урона и пенетры сомнительно, крайне сомнительно, ты сюда добавляешь еще и шаттер сверху, что делает пушку с хорошим АП еще более ебущей из-за эффекта шаттера, который она поддерживает 24/7 из-за своей скорострельности

Чего сомнительного, если это статы до твоего нерфа, и то - даже тогда пушку калом называли. С шаттером возможно соглашусь - чуть-чуть убавить АП.

2024-11-19 17:04 UTC, CheBokJam commented
По запросу из дискордика приблизительное сравнение пушек в идеальных условиях  на воине и на кинге под ферами.

https://github.com/user-attachments/assets/c789e60d-a49f-49c8-a8a4-f54a77f2fb69


https://github.com/user-attachments/assets/4062095f-d850-4d59-963b-c20de9e3ee15

2024-11-19 17:05 UTC, CheBokJam commented on code/modules/projectiles/magazines/specialist.dm
> +	current_rounds = 1000
Коробкам, паверпакам или всему сразу?

2024-11-19 17:07 UTC, homexp13 commented on code/modules/projectiles/magazines/specialist.dm
> +	current_rounds = 1000
паверпаку, патрон меньше, соответственно и дешевле должен быть

2024-11-19 19:10 UTC, CheBokJam commented on code/modules/projectiles/magazines/specialist.dm
> +	current_rounds = 1000
В принципе будто бы ну это эээ как бы плевать?

2024-11-20 08:57 UTC, Istrelok2107 commented
Ебнулся добавлять шаттер?
Шаттер этой хуйне точно не нужен

2024-11-28 15:16 UTC, merged