Shrapnel for marines
PMC-Unga-Marines/Unga-Marines pull request #676
Opened 2024-11-19 21:51 UTC by Istrelok2107

## `Основные изменения`
марам введена удобная подветка для изменения скиллов, также добавлен скилл для марина который в данный момент легко изменять балансно. Марины могут теперь сами доставать шрапу

баланс для самых маленьких
## `Как это улучшит игру`
мары смогут сами ковырять в себе ножичком чтобы достать шрапу
## `Ченджлог`
```
:cl:
qol: легко жонглировать балансом скиллов маринов
balance: Марины теперь могу достать себе шрапу
/:cl:
```
![image](https://github.com/user-attachments/assets/928e0b6d-b847-4256-af05-0657e5cfd7a9)

2024-11-19 22:59 UTC, Helg2 requested changes
Вместе с добавлением нового дефайна, ты также улучшил все взаимодействия медиков, в той же хирургии, обмотке бинтами и т.д. из-за формул использующих кол-во навыка ка кмножитель.

2024-11-19 23:01 UTC, Istrelok2107 commented
> Вместе с добавлением нового дефайна, ты также улучшил все взаимодействия медиков, в той же хирургии, обмотке бинтами и т.д. из-за формул использующих кол-во навыка ка кмножитель.

Ээээ
Похуй? Литл бафф

2024-11-19 23:02 UTC, Istrelok2107 commented
Днем или вечером доделаю, а сейчас спать

2024-11-20 03:23 UTC, Tatarla commented
Распиши ченжлог по людски

2024-11-20 13:44 UTC, LoneAsket commented
Против. Мары и должны сами долго ковырять шрапу. Ради этого и введены и щипцы и допщипцы.

2024-11-20 19:56 UTC, Istrelok2107 commented
> Против. Мары и должны сами долго ковырять шрапу. Ради этого и введены и щипцы и допщипцы
Ты замерял сколько сейчас мар себе ножиком ковыряет шрапу?

2024-11-20 20:47 UTC, closed without merging