Renames Fatty into Oreshnik
PMC-Unga-Marines/Unga-Marines pull request #694
Opened 2024-11-24 12:41 UTC by Etrnlmelancholy

## `Основные изменения`

Переименовывает Фэтти в Орешник.

## `Как это улучшит игру`

В игру добавили ххлов. Почему не добавить орешник. Русифицируем арсенал, чтобы потом русифицировать было меньше. 

## `Ченджлог`
```
:cl:
add: Переименовал Фэтти
/:cl:
```

2024-11-24 12:43 UTC, Etrnlmelancholy commented
как сюда плашку меме повесить

2024-11-24 16:04 UTC, Helg2 commented
Тег в ченжлоге поменяй на `spellcheck`

2024-11-24 16:06 UTC, Etrnlmelancholy commented
сделал

2024-11-24 16:10 UTC, Helg2 commented
И поинформативней.

2024-11-24 18:14 UTC, Etrnlmelancholy commented
Информативно энаугх?

2024-11-24 18:31 UTC, Helg2 commented
Еблан.

2024-11-24 19:20 UTC, Etrnlmelancholy commented
Что блять значит "БОЛЕЕ ИНФОРМАТИВНО", что нахуй непонятно в словах " Переименовал Фэтти в Орешник."

2024-11-24 22:17 UTC, Helg2 commented
![image](https://github.com/user-attachments/assets/84b46f3f-f5da-4d40-ba63-87c1803777d9)
Дохуя информативно

2024-11-25 05:42 UTC, Etrnlmelancholy commented
Ну да. Это часть прикола. В игре оно отображается "Переименовал Фэтти". Челик заходит в игру, смотрит на Фэтти, а там Орешник. Угар

2024-11-28 07:00 UTC, Tatarla commented
Пути в коде переименуй

2024-11-28 22:47 UTC, Helg2 requested changes
"Там каждая ракета подписана под свою категорию, это сделано специально..."

2024-11-29 01:08 UTC, Etrnlmelancholy commented
че блять)

2024-11-29 10:21 UTC, Helg2 commented
Нет, так нет

2024-11-29 10:21 UTC, closed without merging