Crash tweaks
PMC-Unga-Marines/Unga-Marines pull request #727
Opened 2024-11-30 20:55 UTC by CheBokJam

## `Основные изменения`
Много мелких изменений **ДЛЯ КРАША**, основная суть которых сводится к: убийство бесплатных сильнейших феромонов на полкарты, изменение оружейного вендора в сторону такового на дистрессе и добавление АСРС планшета без доступа.

Феромоны
Феро-вышек больше нет (_да и они не нужны были из-за дающего все феры сило_), а сило не выделяет все феромоны максимального уровня (_убираем говно за Ксюшей_), но при этом даёт вдвое урезанную регенерацию (_"Weak", 2 уровень фер, на уровне дрона_). Идея с халявными феромонами может быть хороша для обычных, не лоу-поп режимов, когда морпехи на подходе к сило, но на краше это превращается в кромешный пиздец: ксенос убегает за угол, лечится полностью за 5-10 секунд и выходит из-за угла как ни в чём не бывало ломать лицо морпехам. При этом он имеет бафф к броне и скорости. При этом феры действуют **почти на всей карте**. Особенно комично это смотрится, когда сило находится буквально **в двух шагах от диска/шаттла** (_привет ебанутый спавн шаттла на Биг-Реде в пещерах, привет маленькие карты аля Ресёрч Аутпост_). Сейчас же ксенос не будет регениться за 5 секунд, но при этом не будет и ждать вечность _(привет краш из 2023 года_), чтобы опять выйти в бой.
 (**пометка для депутатов - возможно уровень фер нужно будет повысить с 2 до 3 для адекватного геймплея, имейте в виду**).

Изменения оружейного вендора:
- абсолютно все коробки с патронами, что были в вендоре на дистрессе (ранее АП, ХП коробок не было, но были магазины), теперь есть и здесь;
- добавлены 9мм ХП коробки **И НА ДИСТРЕСС, И НА КРАШ**;
- добавлены поджигающие липучки в количестве 25 (столько же, сколько и обычных липучек); 
- убрана лазерная баттарейка из вкладки "Специализированное", ибо она уже есть во вкладке "Энергетическое"; 
- коробки с флаерами теперь бесконечные; 
- патроны к перцовке теперь бесконечные.

Планшет АСРС.
Я не знаю, кому взбрела в голову идея добавить мутации и карго на краш, но, раз теперь это фишка, и краш стал дистрессом на минималках, то настала пора отвязать карго от спавна синта.
Как это работает сейчас: если синт появляется (_земля бетоном_) - все радуются, карго есть, можно фултонить ксен/буроёбить по пути к диску и заказывать приколы; если синта нет - карго нет, все плачут, ксеносы срут в OOC "Skill issue. Cry baby, cry". ПР добавляет на мостик обоих версий шаттла планшет АСРС без доступа, то есть любой морпех может одобрить/отказать в заказе, поднять/опустить лифт. Это может породить смешные (_не очень_) ситуации, когда дебил решит забрать планшет и станет покупать шмотки только себе, но что делать с такими - все мы знаем.

## `Как это улучшит игру`

Я хуй знает. На краше меньше жопа гореть будет из-за тупых геймплейных решений и фич, изначально задуманных для дистреса, но по нечаянности проникших на краш? А, может, меньше гореть будет из-за исправления оружейного вендора, про который все дружно забыли и забили? В любом случае весь этот ПР - это доработка напильником говна на краше, чтобы краш был более играбелен для мариков.

## `Ченджлог`

```
:cl:
add: На краше в оружейные вендоры добавлены все коробки АХ/ХП (ранее были только магазины) и поджигающие липучки.
add: Добавлены коробки 9мм ХП в оружейные вендоры всех режимов.
add: На краше, на мостиках шаттлов, спавнится специальный карго-планшет без требования к доступу.
del: С краша удалены феро-вышки.
balance: Сило на краше выделяет только рекавери феромоны уровня дрона ("Weak", второй уровень), а дальность этих феромонов повышена с 30 до 50.
balance: На краше коробки с флаерами и патроны к перцовке теперь бесконечны.
/:cl:
```

2024-11-30 21:47 UTC, Helg2 commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/storage/box/m94/cas = -1,
Зачем на краше флаера для каса?

2024-11-30 21:48 UTC, CheBokJam commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/storage/box/m94/cas = -1,
> Зачем на краше флаера для каса?

Чтобы были. Вопрос скорее к тем, кто изначально их туда добавил, я лишь сделал их неограниченными. Плюс у нас теперь время горения у флаеров одинаковое почти.

2024-11-30 21:52 UTC, Helg2 commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/storage/box/m94/cas = -1,
Ну так может следует удалит?

2024-11-30 21:55 UTC, Helg2 requested changes
Вместо планшета добавь просто консоль на мостик. Тогда и не будет возникать ситуаций когда планшет проебался в чьём-то рюкзаке.

2024-11-30 21:56 UTC, CheBokJam commented
> Вместо планшета добавь просто консоль на мостик. Тогда и не будет возникать ситуаций когда планшет проебался в чьём-то рюкзаке.

Дельно

2024-11-30 21:57 UTC, CheBokJam commented on code/game/objects/machinery/vending/marine_vending.dm
> +			/obj/item/storage/box/m94/cas = -1,
Равносильно обычным флаерам, пускай срут разными огоньками, никому от этого хуже не станет

2024-11-30 23:29 UTC, Helg2 commented
Вместо мап эдита сделай подтип в коде.

2024-12-01 12:33 UTC, Helg2 commented on code/modules/reqs/_supply.dm
> +	resistance_flags = 67
Используй дефайн

2024-12-01 12:35 UTC, CheBokJam commented on code/modules/reqs/_supply.dm
> +	resistance_flags = 67
> Используй дефайн

Так числа везде вроде и используются вместо дефайнов, нет? И если делать дефайны, то через list()?

2024-12-01 13:25 UTC, Helg2 commented on code/modules/reqs/_supply.dm
> +	resistance_flags = 67
В числа они конвертируются уже а пост-обработке карты, посмотри как они используются в коде.

2024-12-01 13:49 UTC, CheBokJam commented on code/modules/reqs/_supply.dm
> +	resistance_flags = 67
> В числа они конвертируются уже а пост-обработке карты, посмотри как они используются в коде.

Добавил флаг

2024-12-02 04:32 UTC, Tatarla commented
Депутаты требуют вернуть феры, в остальном пр проходит

2024-12-03 11:46 UTC, Ro2tCrab commented
> > Депутаты требуют вернуть феры, в остальном пр проходит
> 
> 3.14izdec((

Морпехам и пушачек хватит.

2024-12-05 18:04 UTC, Helg2 commented on code/datums/gamemodes/crash.dm
> -		//RUTGMC EDIT END
Из кода тогда также удали феровышку для краша.

2024-12-05 20:04 UTC, CheBokJam commented on code/datums/gamemodes/crash.dm
> -		//RUTGMC EDIT END
Она может в будущем пригодиться, может не надо?

2024-12-05 20:57 UTC, Helg2 commented on code/datums/gamemodes/crash.dm
> -		//RUTGMC EDIT END
Для чего?

2024-12-09 07:45 UTC, merged