Zoom fixes
PMC-Unga-Marines/Unga-Marines pull request #741
Opened 2024-12-03 15:45 UTC by definitelynotspaghetti

## `Основные изменения`

Рефактор зума, префы для вайдскрина

## `Как это улучшит игру`

При зуме больше не будет зависать

## `Ченджлог`

```
:cl:
refactor: Рефактор кода зума
/:cl:
```

2024-12-03 18:35 UTC, Dzhimax commented
> Вайдскрин увеличенный убрать надо, слишком большое преимущество по сторонам

так оно же у всех, пофиг, не? Больше раздражает то, что сверху и снизу мешать смотреть панель с абилками и панель со шмотками, руками и интентами

2024-12-03 18:39 UTC, definitelynotspaghetti commented
> Вайдскрин увеличенный убрать надо, слишком большое преимущество по сторонам

не добавлял его

2024-12-03 18:40 UTC, homexp13 commented
> > Вайдскрин увеличенный убрать надо, слишком большое преимущество по сторонам
> 
> не добавлял его

видать память на цифры подводит

2024-12-04 16:42 UTC, Helg2 requested changes
Мне не нравиться этот пр, так как он оптимизирует не за счёт улучшения кода, а за счёт редактирования значений уже пост фактум.

2024-12-06 08:09 UTC, closed without merging