Tadpole no longer breaks quick build
PMC-Unga-Marines/Unga-Marines pull request #755
Opened 2024-12-04 14:22 UTC by CheBokJam

## `Основные изменения`
Теперь просто вылет ТАДа не отключит быструю застройку, но приземление в любой точке (на ЛЗ, например) после времени открытия створок (обычно в 20 - 22 минут + лаг) - отключит, если ещё не.

## `Как это улучшит игру`
Негры не будут ныть на отключение быстрой застройки из-за вылета ТАДа даже без приземления, а морпехов не будут банить за преждевременный вылет.

## `Ченджлог`

```
:cl:
del: Херобрин удалён.
fix: ТАД больше не ломает быструю застройку при вылете.
/:cl:
```

2024-12-04 15:02 UTC, CheBokJam commented
> Ебланы один хуй вылетают и садятся, фабрику на том же ФОБе делать Прикрути, что если он садится на именно лз, то не ломает тогда квикбилд

Он и так только на ЛЗ и может сесть это раз, а два - я не знаю, есть ли area для ЛЗ всех карт

2024-12-04 15:04 UTC, CheBokJam commented
> Ебланы один хуй вылетают и садятся, фабрику на том же ФОБе делать Прикрути, что если он садится на именно лз, то не ломает тогда квикбилд

Плюсом я не вижу ничего плохого в заводе на земле, ибо вы урезали его до состояния, когда единственная реальная возможность его использования - только на фобе

2024-12-14 17:35 UTC, Helg2 requested changes
Сделай вместо проверки на время, проверку на флаг зоны `MARINE_BASE`
В `/datum/action/ability/activable/xeno/plant_weeds/ranged/can_use_ability` есть пример использования.

2024-12-17 08:50 UTC, CheBokJam commented
Закрываю ПР, ибо Малор сделал лучше

2024-12-17 08:50 UTC, closed without merging