Now crate can be pulled out of the APC.
PMC-Unga-Marines/Unga-Marines pull request #770
Opened 2024-12-05 18:38 UTC by kukurua

## `Основные изменения`

Исправление баг репорта:
https://discord.com/channels/1235677154084126861/1305115948209934416

## `Как это улучшит игру`

Теперь ящики, которые нельзя брать в руки можно не только затащить в БТР, но и вытащить оттуда.

## `Ченджлог`

```
:cl: kukur
fix: Из БТРа теперь можно вытаскивать ящики.
/:cl:
```

2024-12-05 18:58 UTC, Helg2 approved these changes

2024-12-05 20:47 UTC, homexp13 requested changes
есть же easy_load_list, его только дополнить, если я написал херню и через него не работает поправь

2024-12-08 09:49 UTC, kukurua commented
> есть же easy_load_list, его только дополнить, если я написал херню и через него не работает поправь

easy_load_list используется для помещении чего-то В танк или БТР, но при выгрузке чего либо(себя, друзей или ящиков) из танка или БТР код не использует функции, в которых используется easy_load_list.

2024-12-08 12:02 UTC, homexp13 commented
> > есть же easy_load_list, его только дополнить, если я написал херню и через него не работает поправь
> 
> easy_load_list используется для помещении чего-то В танк или БТР, но при выгрузке чего либо(себя, друзей или ящиков) из танка или БТР код не использует функции, в которых используется easy_load_list.

![image](https://github.com/user-attachments/assets/71700dd3-e71d-4731-a008-42b6c6bd8962)
вот как на офах чтобы не только ящики учитывать

2024-12-09 13:04 UTC, Helg2 commented on code/datums/interior/interior_tank.dm
> +		return
Если в результате проверки идёт `return` то `else` использовать нет нужды.

2024-12-09 14:05 UTC, kukurua commented on code/datums/interior/interior_tank.dm
> +		return
Они по факту тут лишние так как в конце всё равно return. Я их уберу сейчас.

2024-12-09 16:05 UTC, Helg2 commented on code/datums/interior/interior_tank.dm
> +		return
У них функционал различается, не лишний

2024-12-09 17:12 UTC, kukurua commented on code/datums/interior/interior_tank.dm
> +		return
Я посмотрел. Там у родителя просто возвращается return.
![изображение](https://github.com/user-attachments/assets/76a7d18b-2873-4ab7-abf6-4e0db39a9e10)

2024-12-10 12:36 UTC, Helg2 commented on code/datums/interior/interior_tank.dm
> +		return
Если мы в будущем добавим родителю какой-либо функционал, то эта интеракция может делать то что не нужно.

2024-12-10 12:39 UTC, homexp13 commented on code/datums/interior/interior_tank.dm
> +		return
просто бы переписал как у офов, я же скрин кинул

2024-12-10 13:18 UTC, kukurua commented on code/datums/interior/interior_tank.dm
> +		return
> просто бы переписал как у офов, я же скрин кинул

Я сначала так и делал, но потом столкнулся с тем, что не все функции на скрине реализованы у нас.
Я оставлю просто return.

2024-12-13 11:37 UTC, Helg2 commented on code/datums/interior/interior_tank.dm
> +	return
```suggestion
	if(ismob(grab.grabbed_thing))
		user.balloon_alert(user, grab.grabbed_thing.name + " thrown outside")
		owner.interior.mob_leave(grab.grabbed_thing)
		return
	if(is_type_in_typecache(grab.grabbed_thing.type, owner.easy_load_list))
		user.balloon_alert(user, "item thrown outside")
		grab.grabbed_thing.forceMove(owner.exit_location(grab.grabbed_thing))
		return
	return ..()
```

2024-12-13 11:54 UTC, merged