Альбедо и Нигредо 2: Медицинский револьвер (дубль 2)
PMC-Unga-Marines/Unga-Marines pull request #774
Opened 2024-12-06 16:05 UTC by siegluck

## `Основные изменения`

**R-312 'Albedo' Revolver**
Второй револьвер из алхимической серии от фирмы BMSS, добрый брат-близнец R-500 'Nigredo' revolver. Может стрелять одним типом боевого патрона и четырьмя типами EMB (experimental medical bullets). Получить его можно за 25 очков вендора санитара или же заказать в карго как отдельно, так и с набором всего необходимого для использования.

Не пытайтесь применять EMB против ксеноморфов! Боеприпасы типа EMB оснащены обратной системой IFF.

**.500 White Express**
Беспороховая модификация .500 Nigro Express, предназначена для использования полевыми медиками в целях самообороны, останавливающая сила патрона способна отбросить не самых тяжёлых ксеноморфов.

Находится в неограниченном количестве в оружейном вендоре во вкладке импорт. Сможете ли вы найти секретную партию коробок этого боеприпаса?

**.500 Adrenaline EMB**
Первый из четырёх боеприпасов типа EMB. Демонстрирует стимулирующее действие на нервную систему и сердце пациента, способна выдернуть морпеха из смертельных лап критического состояния.

**.500 Russian Red EMB**
Боеприпасов типа EMB. Содержит 5 юнитов Russian Red. Применять только в случае крайней необходимости!

BMSS не несёт ответственности за вашу жизнь, если пациент окажется недоволен генетическим уроном, возникшем после применения Russian Red EMB™.

**.500 Meraderm EMB**
Лучший боеприпас EMB на рынке, способный без последствий заживлять множественные повреждения пациента. Содержит 2.5 юнитов Meralyne и 2.5 юнитов Dermaline.

Как и остальные боеприпасы EMB, вы можете приобрести .500 Meraderm EMB™ в отделе снабжения вашего корабля. Не пытайтесь сравнивать цену на набор .500 Meraderm EMB™ с другими источниками Meralyne и Dermaline.

**.500 Neuraline EMB**
Содержит 3.1 юнитов Neuraline и 1.9 Hyronalin. Внимание! Хотя пуля способна достать морпеха из "крита", все токсины от Neuraline нейтрализованы не будут.

**BMSS medkit pouch**
Специально для нового револьвера была разработана улучшенная версия медкит поуча. Она способна вместить не только стандартный медицинский набор, но и коробки с EMB, спидлоудеры с EMB и даже пинцет.

Не хотите платить за револьвер, но хотите наш новый стильный поуч? Всего за 10 очков снабжения вы можете приобрести его отдельно! 

### МИСТЕРЫ КОДЕРЫ, Я ЗАБЫЛ, КАК В ПРОК СТРЕЛЬБЫ ВМЕШАТЬСЯ, ПОПРАВЬТЕ СКИЛЛ ЧЕК ПОЖАЛУЙСТА (591-я строка в code/modules/projectiles/guns/revolvers.dm)

## `Как это улучшит игру`

Легендарный Альбедо снова в игре, медики смешно стреляют в лица морпехов, практическая польза не ясна, нужны тесты (заодно и понять, стоит ли это своих поинтов)

## `Ченджлог`

```
:cl:
add: добавлен медицинский револьвер Альбедо
balance: пули Нигредо летят дальше (вроде бы)
balance: реворк эффекта адреналина в крите, теперь также лечит немного бёрна, но имеет КД поднятия из крита 
/:cl:
```

2024-12-06 17:36 UTC, homexp13 commented on code/modules/projectiles/guns/revolvers.dm
> +		return
сюда return NONE, за место просто ретёрна
. = ..() убираешь

в конце прока return ..() добавляешь

должно работать

2024-12-06 17:41 UTC, homexp13 commented
ещё GUN_ALLOW_SYNTHETIC прописать можно чтобы синты могли пользоваться, но это на усмотрение автора

2024-12-06 17:42 UTC, Helg2 commented on code/game/objects/items/storage/boxes.dm
> +/obj/item/storage/box/t312case/Initialize()
Используй `PopulateContents()` для спавна вещей, заместо `Initialize()`

2024-12-06 17:46 UTC, Helg2 commented on code/game/objects/items/storage/pouch.dm
> +	desc = "Advanced medkit pouch made by BMSS. it also can hold R-312 ammo and tweezers."
```suggestion
	desc = "Advanced medkit pouch made by BMSS. It is also capable of holding R-312 ammo and tweezers."
```

2024-12-06 17:46 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +	staggerstun(M, P, stagger = 0, slowdown = 0, knockback = 0)
Зачем?

2024-12-06 17:47 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +	if(ishuman(M))
Используй ранние ретурны

2024-12-06 17:48 UTC, Helg2 commented on code/modules/projectiles/magazines/misc.dm
> +/obj/item/ammo_magazine/packet/t500/med/
```suggestion
/obj/item/ammo_magazine/packet/t500/med
```

2024-12-06 20:04 UTC, siegluck commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +	staggerstun(M, P, stagger = 0, slowdown = 0, knockback = 0)
Не до конца понял вопрос. Зачем стаггерстан? Поскольку это вариация нигро, у которой есть кнокбек, я его его таким образом убрал, поставив кнокбек 0, потому что медпульки откидывать не должны

2024-12-06 20:05 UTC, siegluck commented
> ещё GUN_ALLOW_SYNTHETIC прописать можно чтобы синты могли пользоваться, но это на усмотрение автора

В принципе можно, но в него можно боевые заряжать, что даст синту возможность стрелять в ксен. Звучит так себе

2024-12-06 20:14 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +	staggerstun(M, P, stagger = 0, slowdown = 0, knockback = 0)
`return` просто пропиши

2024-12-06 20:22 UTC, siegluck commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +	staggerstun(M, P, stagger = 0, slowdown = 0, knockback = 0)
вместо стаггерстана?

2024-12-06 20:27 UTC, Helg2 requested changes
Сделай все что в пути похоже на `/datum/ammo/bullet/revolver/t500/t312` отдельным видом объектов `/datum/ammo/bullet/revolver/t312`

2024-12-06 20:27 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +	staggerstun(M, P, stagger = 0, slowdown = 0, knockback = 1)
```suggestion
/datum/ammo/bullet/revolver/t500/t312/on_hit_mob(mob/M,obj/projectile/P)
	staggerstun(M, P, knockback = 1)
```

2024-12-06 20:27 UTC, Helg2 commented on code/game/objects/items/storage/pouch.dm
> +	icon = 'icons/obj/items/storage/storage.dmi'
```suggestion
```
Ненужное переписывание, совпадает с родителем.

2024-12-06 20:27 UTC, Helg2 commented on code/game/objects/items/storage/boxes.dm
> +	. = ..()
```suggestion
```
Вызов родителя тут не нужен.

2024-12-06 20:27 UTC, Helg2 commented on code/game/objects/items/storage/boxes.dm
> +	icon = 'icons/obj/items/storage/storage.dmi'
```suggestion
```
Ненужное переписывание, совпадает с родителем.

2024-12-06 20:27 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +	if(ishuman(M))
`If(!ishuman(M)) return`

2024-12-06 20:27 UTC, Helg2 commented on code/modules/projectiles/guns/revolvers.dm
> +	allowed_ammo_types = list(/obj/item/ammo_magazine/revolver/t500/t312, /obj/item/ammo_magazine/revolver/t500/med/adrenaline, /obj/item/ammo_magazine/revolver/t500/med/rr, /obj/item/ammo_magazine/revo
Список сделай также как ниже сделан `attachable_allowed`

2024-12-06 20:27 UTC, Helg2 commented on code/modules/projectiles/guns/revolvers.dm
> +	return ..()
Скопируй структуру отсюда, чтобы ничего не сломалось.
![image](https://github.com/user-attachments/assets/e38d7be7-fe39-416d-882a-90fed4250fe6)

2024-12-06 20:27 UTC, Helg2 commented on code/modules/projectiles/magazines/misc.dm
> +	w_class = WEIGHT_CLASS_SMALL
```suggestion
```
Ненужное переписывание, совпадает с родителем.

2024-12-06 20:27 UTC, Helg2 commented on code/modules/reagents/reagents/medical.dm
> +		return
Выше уже есть проверка на КД

2024-12-06 20:29 UTC, Helg2 commented
![image](https://github.com/user-attachments/assets/6fe4a5aa-c169-4f66-b212-ee54a79ac623)
Спрайт пауча всратый.

2024-12-06 23:02 UTC, siegluck commented on code/game/objects/items/storage/pouch.dm
> +	icon = 'icons/obj/items/storage/storage.dmi'
да вроде не совпадает
![image](https://github.com/user-attachments/assets/ab5afd99-4df0-45b3-ac0d-4f8a64165a18)

2024-12-06 23:03 UTC, siegluck commented
> ![image](https://private-user-images.githubusercontent.com/93882977/393395846-6fe4a5aa-c169-4f66-b212-ee54a79ac623.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MjYwNzQsIm5iZiI6MTczMzUyNTc3NCwicGF0aCI6Ii85Mzg4Mjk3Ny8zOTMzOTU4NDYtNmZlNGE1YWEtYzE2OS00ZjY2LWIyMTItZWU1NGE3OWFjNjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDIyNTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYmYzNGNlMGQxNTFkNTUyZmQyMzM3NmMyNzFhZDZmNjVkZmRlMjdhMWZiOGJhZWFjOTBhZjJjODI4Y2Y1OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.caqdalcTSIClZ3lkDDsFF7Trj-kp1J2KD0f7BHmLp1I) Спрайт пауча всратый.

Не всратый
![image](https://github.com/user-attachments/assets/e9bf7bd6-d921-4c19-a516-dc813d048dac)

2024-12-06 23:48 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +	staggerstun(M, P, stagger = 0, slowdown = 0, knockback = 0)
Угу

2024-12-06 23:49 UTC, Helg2 commented on code/game/objects/items/storage/pouch.dm
> +	icon = 'icons/obj/items/storage/storage.dmi'
Со стореджом совпадает

2024-12-06 23:50 UTC, Helg2 commented on code/game/objects/items/storage/pouch.dm
> +	icon = 'icons/obj/items/storage/storage.dmi'
Тогда перемести в файл с паучами xd

2024-12-06 23:51 UTC, Helg2 commented
Ты 3 разных палитры в одном спрайте использовал

2024-12-07 00:47 UTC, siegluck commented on code/game/objects/items/storage/pouch.dm
> +	icon = 'icons/obj/items/storage/storage.dmi'
Я НЕ МОГУ НАЙТИ ЭТОТ ФАЙЛ, ПРОСТИТЕ....

2024-12-07 00:49 UTC, siegluck commented
Спрайт не я делал, ето великий спрайтер Сей, который и спрайтил револьверы, менять его спрайт будет некрасиво, да и смотрится он хорошо. Не уверен, что смогу уменьшить количество задействованных цветов, не испортив спрайт

2024-12-07 00:50 UTC, siegluck commented on code/game/objects/items/storage/pouch.dm
> +	icon = 'icons/obj/items/storage/storage.dmi'
А пути все заменил, надеюсь не пропустил ничего, что могло бы сломать мелочь какую-то, при тестах вроде всё нормально

2024-12-07 01:29 UTC, siegluck commented
Всё, кроме "всратости" поучика, исправил

2024-12-07 14:34 UTC, Helg2 commented
> ето великий спрайтер Сей, который и спрайтил револьверы, менять его спрайт будет некрасиво, да и смотрится он хорошо

Эта хуйня это буквально склеенный из 3 разных паучей пакетик
![image](https://github.com/user-attachments/assets/7fca368e-7332-4ff8-a914-24a1a6513904)

2024-12-07 14:41 UTC, siegluck commented
> Эта хуйня это буквально склеенный из 3 разных паучей пакетик

А проблема в чём? Пояс ревика чёрный, тут тоже чёрный поуч, под стиль ревиков. Ну и добавлен белый цвет для белого ревика

2024-12-07 17:54 UTC, Helg2 commented
Проблема в том что спрайт говно.

2024-12-07 18:41 UTC, siegluck commented
Спрайт не говно, он не нравится лично тебе, другим нравится

2024-12-07 18:56 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +	if(!ishuman(M)) return
Табуляция нужна нормальная, тот пример был таким так как в веб гите ты её не проставишь.

2024-12-07 18:56 UTC, Helg2 commented on code/modules/projectiles/magazines/misc.dm
> +	caliber = CALIBER_500_EMB
```suggestion
```
Совпадает с родителем, ненужное переписывание.

2024-12-07 18:58 UTC, Helg2 commented on code/modules/projectiles/guns/revolvers.dm
> +	attachable_offset = list("muzzle_x" = 0, "muzzle_y" = 0,"rail_x" = 0, "rail_y" = 0, "under_x" = 19, "under_y" = 13, "stock_x" = -19, "stock_y" = 0)
А зачем проставлять оффсеты для атачментов если нацепить можно только шнурок?

2024-12-07 19:06 UTC, siegluck commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +	if(!ishuman(M)) return
типа на следующую строчку перенести ретёрн?

2024-12-07 19:07 UTC, Helg2 commented
> Спрайт не говно, он не нравится лично тебе, другим нравится

Как жаль что они не я.

2024-12-07 19:08 UTC, siegluck commented
> > Спрайт не говно, он не нравится лично тебе, другим нравится
> 
> Как жаль что они не я.

Ну не бери поуч этот в игре, будут брать те, кому он нравится ;)

2024-12-07 19:10 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +	if(!ishuman(M)) return
Угу

2024-12-07 19:28 UTC, CheBokJam commented on code/modules/projectiles/guns/revolvers.dm
> +	attachable_offset = list("muzzle_x" = 0, "muzzle_y" = 0,"rail_x" = 0, "rail_y" = 0, "under_x" = 19, "under_y" = 13, "stock_x" = -19, "stock_y" = 0)
> А зачем проставлять оффсеты для атачментов если нацепить можно только шнурок?

У пушек у всех, вроде бы, ставятся оффсеты на все модули

2024-12-07 19:39 UTC, siegluck commented
ой не то удалил

2024-12-08 14:54 UTC, siegluck commented
Я только не понял, зачем было просить правки в код вносить и заставлять тратить время, если в итоге всё не собираетесь добавлять револьверы по причине "поуч, чей спрайт и так есть в файлах игры, похож на другие поучи, поэтому люди, которым он нравится, могут пососать, как и люди, которым нужен револьвер"

2024-12-08 14:58 UTC, siegluck commented
Или хотя бы блять дайте конкретное описание, что вам в спрайте не нравится, может спрайтер и переделает, потому что никто не понимает, что вообще не так

2024-12-08 14:58 UTC, siegluck commented
![image](https://github.com/user-attachments/assets/5c6288af-52b9-4098-abc5-d4e1759e7ffc)
Спрайтер просит пояснить, что нужно исправить

2024-12-08 15:28 UTC, Helg2 commented
Так как автор спрайта использовал 2 разные не сочетающиеся палитры для основных мест пауча, он выглядит будто сшит из 2-ух других паучей.
Не говоря уже о плохо сочетающейся части спрайта сверху по бокам, наверное это должно обозначать патроны? В любом случае выглядит просто как ещё один лоскут.

2024-12-08 15:53 UTC, siegluck commented
СПРАЙТЕР ГОВОРИТ:

"Так как автор..." - Сочетание палитры хирургического поуча и белта Нигредо не играет никакой роли. Кроме той, что поуч Альбедо имеет двойное назначения - хранения медицины и боеприпасов. А еще в нем можно хранить пинцет.
Кармашек справа тоже в палитре белта Нигредо кстати. Литерали копипаст. 
Плохо сочетающаяся часть спрайта сверху, это поясные лямки которые присутствуют на генерал поучах (аммо, мед, сурджери). Палитра для них была взята с пистолетного поуча, которая так же используется для подобной части на белте Негредо.

2024-12-08 16:19 UTC, siegluck commented
![image](https://github.com/user-attachments/assets/f9815f14-c3a6-4369-8a60-c153ed69e56a)
коробки переспрайтит немного

2024-12-08 18:06 UTC, Helg2 commented
Для обозначения того что поуч вмещает в себя мед. запасы достаточно и креста на видном месте, как это и сделано в мед пауче.

2024-12-08 18:23 UTC, siegluck commented
![image](https://github.com/user-attachments/assets/adf7a815-1785-4368-b2eb-d23628b3c89d)
Подойдёт? Или белый цвет нужно убрать? Просто "Альбедо" значит белый и казалось довольно логичным сделать его поуч с в том числе с белым цветом

2024-12-08 18:26 UTC, Dzhimax commented
![image](https://github.com/user-attachments/assets/878e5c7e-40c2-4d1b-838b-32460e97f75a)

2024-12-08 18:38 UTC, siegluck commented
так лучше?

> Для обозначения того что поуч вмещает в себя мед. запасы достаточно и креста на видном месте, как это и сделано в мед пауче.
![image](https://github.com/user-attachments/assets/619ee531-9f55-45f0-b070-895a3a5ff616)

2024-12-08 18:43 UTC, siegluck commented
проверю чуть попозже, спасиб, что разобрались

2024-12-08 18:49 UTC, Helg2 commented on code/modules/reqs/supplypacks/medical.dm
> +	name = "R-312 packet of .500 Adrenaline EMB"
Упомяни в названиях что в заказе придёт х2 пакетов, либо можно просто уменьшить цену в 2 раза и убрать 2-ой пакет.

2024-12-08 21:11 UTC, siegluck commented
Увеличил максимум горсти с 1 до 5, но теперь коробка выдаёт только сразу 5, доставать по 1 пульке не даёт, переменная used_casings похожа стала пустышкой и пачка с пулями всегда спаунит только полную горсть. Увы

2024-12-08 21:15 UTC, siegluck commented
![image](https://github.com/user-attachments/assets/bff53474-64a0-48b1-89e1-335a7d79d4d0)
Хотелось бы через ПКМ пополнять горсть на 1 штуку, но моих навыков вряд ли хватит на что-то, кроме лютого говнокода. Был бы очень благодарен помощи

2024-12-08 22:57 UTC, siegluck commented
Всё, кроме поштучного пополнения горстей сделано, можно мержить я щитаю

2024-12-09 09:56 UTC, Helg2 commented on code/modules/reqs/supplypacks/medical.dm
> +	name = "R-312 packet of .500 Adrenaline EMB"
Актуально.

2024-12-09 11:00 UTC, CheBokJam commented on code/modules/reqs/supplypacks/medical.dm
> +	name = "R-312 packet of .500 Adrenaline EMB"
> Актуально.

Так в заказе приходит ПАКЕТ и СМЕННЫЙ БАРАБАН, не ДВА ПАКЕТА и не ДВА БАРАБАНА.

2024-12-09 12:43 UTC, siegluck commented
Спидлоадеры работают 
https://cdn.discordapp.com/attachments/1243508837798121482/1315658805006307390/2024-12-09_15-36-48.mp4?ex=6758363e&is=6756e4be&hm=dd65f5572003b98bc96409938191f97e8189c9d53a26ef2e9a83dde6bbbc77fb&

2024-12-12 08:08 UTC, Etrnlmelancholy commented
![image](https://github.com/user-attachments/assets/3ec66141-781f-4cfa-b03f-6a4cb7818c34)

2024-12-12 11:44 UTC, Helg2 commented on code/modules/projectiles/magazines/misc.dm
> +	desc = "Contains 5 units of Russian Red. Use only when absolutely necessary. Heals a large amount of physical damage, but deals cloneless damage."
```suggestion
	desc = "Contains 5 units of Russian Red. Use only when absolutely necessary. Heals a large amount of physical damage, but deals cloneloss damage."
```

2024-12-12 14:19 UTC, siegluck commented
![image](https://github.com/user-attachments/assets/e1dee302-cb8a-4dc5-969c-6dc00279fa59)

2024-12-18 09:37 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +	name = ".500"
```suggestion
	name = ".500 EMB"
```

2024-12-18 09:37 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +/datum/ammo/bullet/revolver/t312/on_hit_mob(mob/M,obj/projectile/P)
```suggestion
/datum/ammo/bullet/revolver/t312/on_hit_mob(mob/M, obj/projectile/P)
```

2024-12-18 09:37 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +/datum/ammo/bullet/revolver/t312/med/on_hit_mob(mob/M,obj/projectile/P)
```suggestion
/datum/ammo/bullet/revolver/t312/med/on_hit_mob(mob/M, obj/projectile/P)
```

2024-12-18 09:37 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +/datum/ammo/bullet/revolver/t312/med/adrenaline/on_hit_mob(mob/M,obj/projectile/P)
```suggestion
/datum/ammo/bullet/revolver/t312/med/adrenaline/on_hit_mob(mob/M, obj/projectile/P)
```

2024-12-18 09:37 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +/datum/ammo/bullet/revolver/t312/med/rr/on_hit_mob(mob/M,obj/projectile/P)
```suggestion
/datum/ammo/bullet/revolver/t312/med/rr/on_hit_mob(mob/M, obj/projectile/P)
```

2024-12-18 09:37 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +/datum/ammo/bullet/revolver/t312/med/md/on_hit_mob(mob/M,obj/projectile/P)
```suggestion
/datum/ammo/bullet/revolver/t312/med/md/on_hit_mob(mob/M, obj/projectile/P)
```

2024-12-18 09:37 UTC, Helg2 commented on code/modules/projectiles/ammo_datums/bullet/revolver.dm
> +/datum/ammo/bullet/revolver/t312/med/neu/on_hit_mob(mob/M,obj/projectile/P)
```suggestion
/datum/ammo/bullet/revolver/t312/med/neu/on_hit_mob(mob/M, obj/projectile/P)
```

2024-12-18 09:37 UTC, Helg2 commented on code/modules/projectiles/guns/revolvers.dm
> +		/obj/item/ammo_magazine/revolver/t312/med/neu)
```suggestion
	allowed_ammo_types = list(
		/obj/item/ammo_magazine/revolver/t312,
		/obj/item/ammo_magazine/revolver/t312/med/adrenaline,
		/obj/item/ammo_magazine/revolver/t312/med/rr,
		/obj/item/ammo_magazine/revolver/t312/med/md,
		/obj/item/ammo_magazine/revolver/t312/med/neu
	)
```

2024-12-18 09:37 UTC, Helg2 commented on code/modules/projectiles/guns/revolvers.dm
> +	if (!.)
```suggestion
	if(!.)
```

2024-12-18 09:37 UTC, Helg2 commented on code/__DEFINES/loadout.dm
> +	/obj/item/storage/pouch/medkit/t312 = list(CAT_MEDSUP, "Medkit pouch for EMB", 1, "blue"),
Так ли нужен пауч в вендоре, если он есть бесплатно так и в карго за 10 очков?

2024-12-18 09:37 UTC, Helg2 commented on code/__DEFINES/loadout.dm
> +	/obj/item/ammo_magazine/packet/t312/med/neu = list(CAT_MEDSUP, "packet of .500 Neuraline EMB", 10, "orange2"),
Подними цену самому Альбедо и соразмерно опусти цену пакетам, допустим револьвер до 15 и пакеты на 2-3 поинта снизить, револьвер достаточно сильный и сам по себе с боевыми патронами.

2024-12-19 15:24 UTC, Furrytomat commented on code/__DEFINES/loadout.dm
> +	/obj/item/ammo_magazine/packet/t312/med/neu = list(CAT_MEDSUP, "packet of .500 Neuraline EMB", 10, "orange2"),
Это пиздец....

2024-12-20 18:32 UTC, siegluck commented on code/__DEFINES/loadout.dm
> +	/obj/item/ammo_magazine/packet/t312/med/neu = list(CAT_MEDSUP, "packet of .500 Neuraline EMB", 10, "orange2"),
бред полный, вопрос баланса

2024-12-20 18:33 UTC, siegluck commented on code/__DEFINES/loadout.dm
> +	/obj/item/storage/pouch/medkit/t312 = list(CAT_MEDSUP, "Medkit pouch for EMB", 1, "blue"),
да нужен, игрок может захотеть из вендра взять поучи с шприцами

2024-12-20 19:17 UTC, siegluck commented
замерджите уже нормально умоляю

2024-12-21 12:20 UTC, Helg2 approved these changes

2024-12-21 12:21 UTC, Helg2 commented
Легче будет за тобой самому хуйню убрать.

2024-12-21 12:21 UTC, merged