Musket return
PMC-Unga-Marines/Unga-Marines pull request #799
Opened 2024-12-10 16:16 UTC by CheBokJam

## `Основные изменения`
Порт https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/348#issue-2080333788 за авторством Фида и Кроу.
СО и капитан при спавне получают мушкетон и мушкет соответственно, а также мешочки с патронами к ним: СО получает малый мешочек с 27 снарядами, а кэп - большой на 54. Мешки с патронами получить кроме спавна ещё одной из вышеперечисленных ролей нельзя, как и их особые пушки, потеряли/израсходовали весь БК - увы.
По своей сути пушки являются разновидностями Мартини Генри.

![dreamseeker_YEG2eZxjt3](https://github.com/user-attachments/assets/58f3b117-6854-480a-8cd9-e6d5f8bff027)

## `Как это улучшит игру`
Больше уникальных пушек - лучше?

## `Ченджлог`

```
:cl:
add: СО и капитан спавнятся с мушкетоном и мушкетом соответственно, а также с мешочками патронов к ним.
/:cl:
```

2024-12-10 16:17 UTC, MalorMorfin commented
Не говорите ему что таких "уникальных" пушек целое карго в вкладке импорт... (игра не лучше)

2024-12-10 21:26 UTC, Helg2 commented
Прикрути зарядке задержку секунды в 4, а то 220 урона с ограничением лишь в виде 0.5 вилда слишком сильно.

2024-12-11 09:48 UTC, CheBokJam commented
> Прикрути зарядке задержку секунды в 4, а то 220 урона с ограничением лишь в виде 1 секунды вилда, которым можно пренебречь, слишком сильно.

Хорошая мысль, тогда и спрайт пушки будет выглядеть так, будто заряжают с дула кремниевое ружье. Один нюанс - 4 звучит много, ибо там задержка взятия в руки 1с и задержка перед выстрелом 2с (она, наверное, при задержке перезарядки не будет нужна вообще).

2024-12-11 10:46 UTC, Helg2 commented
> Хорошая мысль, тогда и спрайт пушки будет выглядеть так, будто заряжают с дула кремниевое ружье. Один нюанс - 4 звучит много, ибо там задержка взятия в руки 1с и задержка перед выстрелом 2с (она, наверное, при задержке перезарядки не будет нужна вообще).

`fire_delay` отвечает не за задержку перед выстрелом а за кд между выстрелами, за задержку отвечает `windup_delay` или что-то подобное.

2024-12-11 11:36 UTC, CheBokJam commented
> > Хорошая мысль, тогда и спрайт пушки будет выглядеть так, будто заряжают с дула кремниевое ружье. Один нюанс - 4 звучит много, ибо там задержка взятия в руки 1с и задержка перед выстрелом 2с (она, наверное, при задержке перезарядки не будет нужна вообще).
> 
> `fire_delay` отвечает не за задержку перед выстрелом а за кд между выстрелами, за задержку отвечает `windup_delay` или что-то подобное.

Ну да, я клонил к тому, что КД тогда не нужно будет при вводе долгой перезарядке

2024-12-11 11:38 UTC, CheBokJam commented
> > Хорошая мысль, тогда и спрайт пушки будет выглядеть так, будто заряжают с дула кремниевое ружье. Один нюанс - 4 звучит много, ибо там задержка взятия в руки 1с и задержка перед выстрелом 2с (она, наверное, при задержке перезарядки не будет нужна вообще).
> 
> `fire_delay` отвечает не за задержку перед выстрелом а за кд между выстрелами, за задержку отвечает `windup_delay` или что-то подобное.

Короче, в этом ПРе менять прок, отвечающий за генерацию горстей патронов, чтобы он учитывал ещё и var/reload_delay, я не буду. Сейчас я просто задержку взятия в руки изменю, а потом, если мержнут ПР с изменением прока, уже допилю этот.

2024-12-16 17:46 UTC, Helg2 commented on code/modules/projectiles/magazines/misc.dm
> +	icon_state_mini = "musket_sack_s"
```suggestion
	desc = "A small sack filled with lead bullets."
	icon_state = "musket_sack_s"
	max_rounds = 27
	w_class = WEIGHT_CLASS_TINY
	icon_state_mini = "musket_sack_s"
```
Совпадает с родителем.

2024-12-16 17:46 UTC, Helg2 commented on code/modules/projectiles/guns/shotguns.dm
> +	default_ammo_type = /datum/ammo/bullet/sniper/musket
```suggestion
```
Совпадает с родителем.

2024-12-16 17:47 UTC, Helg2 commented on code/modules/projectiles/guns/shotguns.dm
> +	)
Перемести спрайты в иконки для оружия.

2024-12-16 17:47 UTC, Helg2 commented on code/modules/projectiles/guns/shotguns.dm
> +	caliber = CALIBER_19MM
```suggestion
```
Совпадает с родителем.

2024-12-16 17:49 UTC, Helg2 requested changes
Повысь размер мешков с пулями и пистоля на 1.

2024-12-19 12:16 UTC, merged