Quick build work until TAD lands off the LZ.
PMC-Unga-Marines/Unga-Marines pull request #824
Opened 2024-12-15 10:17 UTC by MalorMorfin

## `Основные изменения`
Тад при посадке на ЛЗ не сломает быструю застройку черным существам

## `Как это улучшит игру`
Ксеносы перестанут подрываться на каждую сломанную застройку.

## `Ченджлог`

```
:cl:
fix: Теперь тад не ломает застройку пока садится на ЛЗ
/:cl:
```

2024-12-15 16:21 UTC, Helg2 commented on code/modules/shuttle/mini_dropship.dm
> -	clean_ui_user()
?

2024-12-15 16:22 UTC, Helg2 commented on code/modules/shuttle/mini_dropship.dm
> -	SEND_GLOBAL_SIGNAL(COMSIG_GLOB_TADPOLE_LAUNCHED)
В будущем могло бы пригодиться.

2024-12-15 16:32 UTC, MalorMorfin commented on code/modules/shuttle/mini_dropship.dm
> -	clean_ui_user()
Короче, каждый раз при открытии менюшки взлёта, , и например при движении, прок закрытия вызывался по 2 раза, Из-за этого было куча рантаймов, не знал как нормально и красиво исправить, решил так, там ещё снизу где теперь стоит сенд сигнал, после close UI стоит этот прок

2024-12-15 16:34 UTC, MalorMorfin commented on code/modules/shuttle/mini_dropship.dm
> -	SEND_GLOBAL_SIGNAL(COMSIG_GLOB_TADPOLE_LAUNCHED)
Закоментить? Просто думаю если бы людям понадобилось заново написал, там вроде не так сложно, по примеру посадки.

2024-12-15 16:39 UTC, Helg2 commented on code/modules/shuttle/mini_dropship.dm
> -	SEND_GLOBAL_SIGNAL(COMSIG_GLOB_TADPOLE_LAUNCHED)
Комменти

2024-12-15 16:48 UTC, Helg2 commented on code/modules/shuttle/mini_dropship.dm
> -	clean_ui_user()
Я не совсем понимаю какие из-за этого могут быть рантаймы, можешь скинуть скрины?

2024-12-15 17:13 UTC, MalorMorfin commented on code/modules/shuttle/mini_dropship.dm
> -	clean_ui_user()
> Я не совсем понимаю какие из-за этого могут быть рантаймы, можешь скинуть скрины?

нулы, щяс скину в этом комменте чуть позже

2024-12-15 17:48 UTC, MalorMorfin commented on code/modules/shuttle/mini_dropship.dm
> -	clean_ui_user()
> Я не совсем понимаю какие из-за этого могут быть рантаймы, можешь скинуть скрины?
Первый скрин - ошибка
Второй скрин - там где щяс стрелка, активирует прок закрытия UI, src объекта, тоесть активирует прок ui_close, который запускает процесс заново, из-за чего, после прохождения прока на котором стрелка, дальше ui_user идет нуллом. А там и ошибка с первого скрина появляется, короче прок по 2 раза работает...
![image](https://github.com/user-attachments/assets/921cb738-e048-421e-8280-5d431921cf5c)
![image](https://github.com/user-attachments/assets/4c69ba34-1ff0-425c-b851-0bebc15b1a7c)

2024-12-16 04:09 UTC, MalorMorfin commented
что за сюр, все работало, сейчас просто меняю положение коммента для перезапуска теста, а ошибок все больше, почему вообще ласт стенд умер... а кутово...

2024-12-16 14:28 UTC, MalorMorfin commented
Есть правда вопросик почему оно не проходило тесты, например на ласт стенде, где я например ничего не менял, и норма ли это вообще, если та часть кода не была тронута...

2024-12-18 22:32 UTC, Helg2 approved these changes

2024-12-18 22:34 UTC, Helg2 commented on code/modules/shuttle/mini_dropship.dm
>  	. = ..()
```suggestion
```
Ничего не делает ведь

2024-12-18 22:35 UTC, Helg2 requested changes
Выше

2024-12-19 11:52 UTC, Helg2 approved these changes

2024-12-19 11:52 UTC, merged