New tad "Barga"
PMC-Unga-Marines/Unga-Marines pull request #858
Opened 2024-12-21 18:37 UTC by cnaper-dodo

## `Основные изменения`

Добовления нового тада-Баржи.Не имеет внутренние и внешние оружейные крепления,но имеет значительный внутренний обьем.
## `Как это улучшит игру`

Большой тад.Мини нормандия.Гы-гы
## `Ченджлог`

```
:cl:
add: Добавил новый тад

/:cl:
```

2024-12-21 18:38 UTC, cnaper-dodo commented
![Снимок экрана 2024-12-21 233523](https://github.com/user-attachments/assets/9f4577b8-6a8a-487b-88f3-5f54e5b9bf9c)

2024-12-23 08:49 UTC, Helg2 commented on code/datums/shuttles.dm
> +	display_name = "Tadpole Barga Model"
```suggestion
	display_name = "Tadpole Barga Model"

```

2024-12-23 08:49 UTC, Helg2 commented on code/datums/shuttles.dm
> +	description = "A cargo barge used for transporting significant forces.The combat modules were sacrificed for the sake of the internal volume."
```suggestion
	description = "A cargo barge used for transporting significant forces. The combat modules were sacrificed for the sake of the internal volume."
```

2024-12-23 08:50 UTC, Helg2 commented
![image](https://github.com/user-attachments/assets/89fe5756-4408-41d0-98a0-320cc2ddfc1f)
Лишние напольные лампочки можно удалить/переместить

![image](https://github.com/user-attachments/assets/87ca78ff-d56d-431d-ac47-196d931c1984)
В окнах отсутствуют створки против космоса.

Пожарный шкафчик всё также нельзя достичь, так как он висит сильно севернее его реального местоположения.

Формат карты нужно поменять.

2024-12-23 14:56 UTC, cnaper-dodo commented
> ![image](https://private-user-images.githubusercontent.com/93882977/398106161-89fe5756-4408-41d0-98a0-320cc2ddfc1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjYxMDUsIm5iZiI6MTczNDk2NTgwNSwicGF0aCI6Ii85Mzg4Mjk3Ny8zOTgxMDYxNjEtODlmZTU3NTYtNDQwOC00MWQwLTk4YTAtMzIwY2MyZGRmYzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE0NTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNGZmYzA2YzRjYmI1N2Y5MjI0ODgzMmVlNGQ1MThhNzVlZjc2ZDJhODI2Njg1ZTE2ZDU3YmQzZDYxYjNmMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WJzn-4hvDorJqoIP42qaWTbsPuUCTg1QJABYprgs5tM) Лишние напольные лампочки можно удалить/переместить
> 
> ![image](https://private-user-images.githubusercontent.com/93882977/398106737-87ca78ff-d56d-431d-ac47-196d931c1984.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjYxMDUsIm5iZiI6MTczNDk2NTgwNSwicGF0aCI6Ii85Mzg4Mjk3Ny8zOTgxMDY3MzctODdjYTc4ZmYtZDU2ZC00MzFkLWFjNDctMTk2ZDkzMWMxOTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE0NTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YmRlZThmZjgwYzc2OTM1YmI1ZTVmZmQxMzEzNWIxOTc4ZDYzMTBlOWYxNzcyZTIzZTNkY2MxNDRkMzlkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mvCHtwtKQ_CJ91Sde88pPxGId7z40HCI0emrubz0sU8) В окнах отсутствуют створки против космоса.
> 
> Пожарный шкафчик всё также нельзя достичь, так как он висит сильно севернее его реального местоположения.
> 
> Формат карты нужно поменять.

Все сделал.

2024-12-26 14:44 UTC, Helg2 commented
Замечания актуальны, также нужно обновить картинку.

2024-12-26 20:32 UTC, Helg2 requested changes
Также замени `barga` на `barge`

2024-12-26 21:17 UTC, cnaper-dodo commented
![Снимок экрана 2024-12-27 020024](https://github.com/user-attachments/assets/6c181f9e-b171-459b-8645-893d5956024d)
![Снимок экрана 2024-12-27 020020](https://github.com/user-attachments/assets/c5ff3f30-973a-45b7-a12d-f38a8a454e11)

2024-12-26 21:39 UTC, Helg2 approved these changes

2024-12-26 21:39 UTC, merged