Crach ship apdeir
PMC-Unga-Marines/Unga-Marines pull request #875
Opened 2024-12-25 03:29 UTC by cnaper-dodo

## `Основные изменения`

На корабли для краша добавлена полноценная? химия,добавлен 2 слот для стационарного вооруженея.
## `Как это улучшит игру`
как то?

## `Ченджлог`

```
:cl:
map: Изменил корабли для краша
/:cl:
```

2024-12-25 03:30 UTC, cnaper-dodo commented
![Снимок экрана 2024-12-25 083042](https://github.com/user-attachments/assets/6ea66ce1-562e-42ef-a614-99bd1c6bd0df)
![Снимок экрана 2024-12-25 083033](https://github.com/user-attachments/assets/c2788067-7a2d-4f38-96e8-fd55127f1ac4)

2024-12-25 05:41 UTC, CheBokJam commented
А зачем ты убрал автодок с Кэнтберри? Чтобы люди без СМО/синта абалдели от невозможности восстановить органы, вырезать хаггера и пр? Химия не того не стоит

2024-12-25 06:34 UTC, F0rbet commented
Да, автодок нужно оставить

2024-12-25 07:17 UTC, cnaper-dodo commented
@F0rbet @CheBokJam ваши слова услышал переделал

2024-12-25 07:18 UTC, cnaper-dodo commented
![Снимок экрана 2024-12-25 121723](https://github.com/user-attachments/assets/54e2bf17-8d6e-4620-a38d-bb0e2adb69f4)
![Снимок экрана 2024-12-25 083033](https://github.com/user-attachments/assets/236db0b4-3444-4314-856b-28851d721fb1)

2024-12-26 20:34 UTC, Helg2 requested changes
Кантерберри лучше расширить, нежели удалять одни вещи и заменяя их другими.
Название и ченжлог сделай информативными.

2024-12-26 21:23 UTC, CheBokJam commented
> Кантерберри лучше расширить, нежели удалять одни вещи и заменяя их другими. Название и ченжлог сделай информативными.

Та зачем его делать больше - со своей задачей Кентберри справляется отлично. Я бы лично добавил румбу с компом, который выдаёт засосанные румбой вещи, ибо на кораблях часто всё засирается и начинает лагать.

2024-12-27 04:34 UTC, Tatarla commented
Надо в целом корабли краша заменить на 1 нормально сделанный шип со всеми удобствами

2024-12-27 06:07 UTC, cnaper-dodo commented
> Надо в целом корабли краша заменить на 1 нормально сделанный шип со всеми удобствами

Блядь,тимшиз.На всех кораблях есть все удобства,просто они с разным онлайном...
Ладно седня посижу подумаю

2024-12-27 07:20 UTC, CheBokJam commented
Проебал проводку и лампочка над ведром одежды под крио висит

2024-12-27 08:38 UTC, Helg2 commented
А зачем ты поменял стороны у кантербери?

2024-12-27 13:13 UTC, cnaper-dodo commented
![image](https://github.com/user-attachments/assets/d7386cdf-5279-4348-b7f8-a74da5ec7603)
Запрос людей.Итог

2025-01-04 12:12 UTC, closed without merging